const q=(domain,topic,prompt,correct,wrong1,wrong2,wrong3,explanation,source)=>[domain,topic,prompt,correct,wrong1,wrong2,wrong3,explanation,source];

const general=[
q("Licensing and rules","License classes","Which rating determines whether a heavy combination meets the Class A threshold?","The combined gross combination weight rating and the towed unit rating","The tractor fuel capacity only","The number of trailer doors","The vehicle's empty scale weight only","Class A classification is based on rated combination weight and the rating of the towed unit.","Nebraska Specifics, CDL Classes"),
q("Licensing and rules","Learner permit","Who must accompany a driver practicing with a commercial learner's permit?","A properly licensed CDL holder qualified for that vehicle","Any adult passenger","A mechanic without a CDL","Another learner-permit holder","A CLP holder must be supervised by a CDL holder qualified to operate the vehicle.","Nebraska Specifics, Commercial Learner's Permit"),
q("Licensing and rules","Learner permit","What must a CLP applicant complete before receiving endorsements on the permit?","All applicable written knowledge tests","The road test only","A vehicle registration inspection only","No testing until the CDL is issued","Nebraska requires the applicable knowledge tests before issuing the requested CLP class and endorsements.","Nebraska Specifics, CLP Testing"),
q("Licensing and rules","Endorsements","Which endorsement is required to operate a tank vehicle as defined by CDL rules?","N - Tank Vehicle","T - Doubles/Triples","P - Passenger","S - School Bus","The N endorsement authorizes operation of a qualifying tank vehicle.","Nebraska Specifics, CDL Endorsements"),
q("Licensing and rules","Restrictions","What does a P restriction on a commercial learner's permit mean?","No passengers may be carried except as allowed for training or testing","No parking on public roads","No pneumatic brakes","No nighttime operation","The CLP passenger restriction prevents ordinary passenger transportation during permit operation.","Nebraska Specifics, CLP Restrictions"),
q("Licensing and rules","Restrictions","What does an O restriction prevent a CDL holder from operating?","A tractor-trailer combination","A vehicle with air brakes","A passenger bus","An intrastate truck","An O restriction is the except-tractor-trailer restriction.","Nebraska Specifics, CDL Restrictions"),
q("Licensing and rules","Medical certification","Why must a CDL holder report the correct self-certification category?","It determines which medical certification requirements apply","It sets the vehicle's tire pressure","It replaces all endorsements","It selects a fuel-tax rate","The operating category determines whether a valid medical certification must be maintained.","Nebraska Specifics, Certification and Medical Information"),
q("Licensing and rules","Disqualification","What can result from leaving the scene of a crash while operating a commercial vehicle?","CDL disqualification as a major offense","Automatic addition of a passenger endorsement","A warning with no CDL consequence","Cancellation of the vehicle title only","Leaving a crash scene is among the major offenses that can disqualify a commercial driver.","Section 1.3, Driver Disqualifications"),
q("Licensing and rules","Disqualification","Why must a commercial driver notify an employer of certain traffic convictions?","CDL rules require timely reporting of convictions","The employer pays every fine","It renews the vehicle registration","It replaces court reporting","Commercial drivers have reporting duties so employers know about qualifying convictions.","Section 1.2, Driver Responsibilities"),
q("Licensing and rules","Testing","What must be true of the vehicle used for a CDL skills test?","It must represent the class and type of vehicle sought","It must always be empty","It must be owned by the DMV","It must be less than one year old","Skills testing must demonstrate ability in a representative commercial vehicle.","Nebraska Specifics, CDL Skills Testing"),
q("Licensing and rules","ELDT","When is entry-level driver training required for a first-time Class A or Class B applicant?","Before the required CDL skills test","Only after the CDL expires","After every annual inspection","Only when adding air brakes","Federal ELDT must be completed and verified before qualifying first-time skills testing.","Nebraska Specifics, Entry Level Driver Training"),
q("Licensing and rules","Documents","Why should an applicant bring original or certified identity documents?","Nebraska does not accept ordinary photocopies for identity verification","Photocopies increase license fees","Only employers may make copies","The documents are used to calculate vehicle weight","Nebraska requires acceptable original or certified documents and rejects ordinary copies.","Nebraska Specifics, Document Verification"),

q("Inspection and cargo","Inspection","What should a driver do when an inspection finds a safety defect?","Correct it before operating when the defect makes the vehicle unsafe","Hide it from the inspection report","Drive until the next annual inspection","Compensate by increasing speed","An unsafe vehicle must not be placed in service until critical defects are corrected.","Section 2.1, Vehicle Inspection"),
q("Inspection and cargo","Inspection","Why inspect the area around a vehicle before moving?","To identify people, obstacles, leaks, and low clearances","To warm the service brakes","To reset the odometer","To measure cargo temperature only","A walk-around reveals hazards that may be invisible from the driver's seat.","Section 2.1, Seven-step Inspection Method"),
q("Inspection and cargo","Inspection","What should wheel fasteners be checked for?","Missing, loose, damaged, or rust-streaked fasteners","Matching paint color","A warm temperature only","Extra grease on the tire tread","Loose or damaged fasteners can allow a wheel to fail or separate.","Section 2.1, Wheels and Rims"),
q("Inspection and cargo","Inspection","What does oil or grease on a brake lining suggest?","A seal or component leak that can reduce braking","Correct brake adjustment","Normal tire wear","An overfilled fuel tank","Contaminated brake linings may not develop adequate friction.","Section 2.1, Brake Inspection"),
q("Inspection and cargo","Cargo","Why should cargo weight be distributed across the vehicle?","To maintain legal axle loads and stable handling","To make the rear axle carry everything","To eliminate the need for tiedowns","To increase the posted speed limit","Balanced distribution protects components and helps steering and braking remain predictable.","Section 3.2, Weight and Balance"),
q("Inspection and cargo","Cargo","What is the role of blocking and bracing?","Prevent cargo from sliding, shifting, or rolling","Increase the cargo's legal weight","Replace vehicle inspection","Keep trailer doors unlocked","Blocking and bracing work with securement to control cargo movement.","Section 3.3, Blocking and Bracing"),
q("Inspection and cargo","Cargo","Why must tiedowns be attached to proper anchor points?","Weak or unsuitable points can fail under cargo forces","Any painted surface is equally strong","Anchor points determine fuel mileage only","Loose attachment makes unloading faster","Securement is only as strong as the structures to which it is attached.","Section 3.3, Cargo Securement"),
q("Inspection and cargo","Cargo","What should be checked after cargo is loaded into a closed trailer?","That doors latch securely and cargo cannot force them open","That the doors remain partly open","That no tiedowns are used","That all weight is placed against one wall","Doors and cargo must be secured so freight cannot escape in motion.","Section 3.3, Cargo Securement"),

q("Driving and control","Starting","What is the safest way to start moving from a parked position?","Check around the vehicle, signal, and move only when the path is clear","Accelerate before checking mirrors","Rely only on the horn","Enter traffic without signaling","A complete scan and signal give the driver and other road users time to avoid conflict.","Section 2.2, Basic Control"),
q("Driving and control","Shifting","Why should a driver avoid coasting in neutral?","It removes engine braking and may delay selecting the proper gear","It improves steering control","It shortens every stop","It charges the air tanks faster","Remaining in gear preserves control and engine braking.","Section 2.3, Shifting Gears"),
q("Driving and control","Seeing","What is the purpose of scanning far ahead and then back toward the vehicle?","It combines early hazard detection with awareness of nearby conditions","It removes the need for mirrors","It lets the driver ignore lane markings","It measures vehicle height","An organized scan identifies developing hazards without losing track of immediate traffic.","Section 2.4, Seeing"),
q("Driving and control","Mirrors","When are mirror checks especially important?","Before and during lane changes, turns, merges, and tight maneuvers","Only after parking","Only on empty roads","Only when another driver sounds a horn","Frequent mirror use reveals vehicles and objects entering the CMV's blind areas.","Section 2.4, Using Mirrors"),
q("Driving and control","Communication","How can a stopped commercial vehicle warn approaching traffic?","Use required flashers and properly placed warning devices","Turn off all exterior lights","Place a warning device inside the cab","Rely only on reflective cargo","Visible lights and warning devices give traffic time and distance to react.","Section 2.5, Communicating"),
q("Driving and control","Speed","Why must speed be reduced on a rough roadway?","Bumps can reduce tire contact and cause loss of control or cargo damage","Rough roads improve braking","The speed limit doubles on bumps","Suspension movement lowers the center of gravity","Lower speed reduces the forces caused by potholes, dips, and uneven pavement.","Section 2.6, Road Conditions"),
q("Driving and control","Speed","How should speed change when traction is reduced?","Slow enough to steer and stop within the available grip","Increase to cross the surface quickly","Keep the same speed in every condition","Use cruise control to prevent adjustments","Reduced traction requires lower speed and greater space.","Section 2.6, Controlling Speed"),
q("Driving and control","Following distance","What extra following-distance adjustment is needed in rain or snow?","Add space beyond the normal vehicle-length rule","Subtract one second","Follow closely to see taillights","Use the same distance as dry pavement","Poor traction and visibility increase the time and distance needed to respond.","Section 2.7, Following Distance"),
q("Driving and control","Space management","Why should a driver avoid entering an intersection without room to clear it?","The long vehicle could block traffic or railroad tracks","The signal will remain green longer","It improves turning clearance","It reduces offtracking","A driver must ensure the entire CMV can clear before entering a confined intersection.","Section 2.7, Space Ahead"),
q("Driving and control","Turns","What should be checked immediately after completing a turn?","Mirrors for trailer tracking, traffic, and clearance","Only the fuel gauge","The sleeper compartment","Only the radio","Post-turn mirror checks confirm the rear of the vehicle cleared hazards and returned to the lane.","Section 2.7, Turns"),
q("Driving and control","Railroad crossings","Why should a driver know the vehicle's length before crossing tracks?","To ensure enough space exists on the far side for the whole vehicle","To calculate tire pressure","To select a radio station","To avoid using mirrors","A long vehicle must not enter unless it can completely clear every rail.","Section 2.15, Railroad-highway Crossings"),
q("Driving and control","Mountain driving","Why is the posted downgrade speed not automatically safe for every CMV?","Safe speed also depends on weight, grade, road, and weather","All commercial vehicles weigh the same","Posted speeds apply only uphill","Air brakes eliminate grade risk","The driver must choose a speed appropriate for the specific vehicle and conditions.","Section 2.16, Mountain Driving"),
q("Driving and control","Braking","What is stab braking when ABS is unavailable?","Apply fully, release when wheels lock, and reapply after they roll","Hold the parking brake continuously","Pump the accelerator while coasting","Use only the trailer hand valve","Stab braking alternates full application and release to regain rolling traction.","Section 2.17, Emergency Braking"),
q("Driving and control","ABS","What should a driver do if the ABS warning light stays on after its normal check?","Have the ABS inspected while remembering normal brakes still function","Assume all brakes have failed","Remove the warning bulb","Use the parking brake for every stop","A persistent light indicates an ABS fault, not loss of the basic brake system.","Section 2.18, Antilock Braking Systems"),
q("Driving and control","Skids","Why should steering be corrected promptly after a rear-wheel skid begins?","The vehicle can swing farther out of line if the skid grows","Steering has no effect during a skid","The engine will stop automatically","The brakes become cooler","Early controlled correction improves the chance of restoring alignment before a jackknife develops.","Section 2.19, Skid Control"),
q("Driving and control","Backing","Why should backing begin from the best possible setup?","Good positioning reduces blind-side movement and correction","It eliminates the need to look","It makes spotters unnecessary","It increases trailer offtracking","A planned setup keeps the path visible and minimizes difficult steering changes.","Section 2.2, Backing Safely"),
q("Driving and control","Parking","What should be done before leaving the driver's seat?","Set the parking brakes and secure the vehicle against movement","Leave the transmission in neutral only","Release every brake","Keep the engine at high idle","The driver must prevent unintended movement whenever leaving the controls.","Section 2.2, Parking"),

q("Hazards and conditions","Hazard perception","Why should a driver watch parked vehicles and roadside activity?","People or vehicles may enter the lane without warning","Parked vehicles always have the right of way","Roadside activity improves traction","It replaces checking mirrors","Clues near the roadway can reveal hazards before they move into the CMV's path.","Section 2.8, Seeing Hazards"),
q("Hazards and conditions","Work zones","What should a driver expect when approaching a lane closure?","Early merging instructions, reduced space, and sudden slowing","Wider lanes and higher speeds","No workers near traffic","A guaranteed open shoulder","Work zones require early observation, lower speed, and extra following distance.","Section 2.8, Work Zones"),
q("Hazards and conditions","Night driving","Why can overdriving headlights cause a crash?","Stopping distance may exceed the distance visible ahead","Headlights shorten reaction time","High beams always stop the vehicle","Brakes become stronger at night","Speed must allow the vehicle to stop within the illuminated roadway.","Section 2.11, Driving at Night"),
q("Hazards and conditions","Fog","What should a driver do if fog becomes too dense for safe travel?","Leave the roadway at a safe place and stop","Use high beams and continue at the limit","Follow taillights closely","Stop in a travel lane","When visibility is inadequate, the safest choice is to stop well away from moving traffic.","Section 2.11, Driving in Fog"),
q("Hazards and conditions","Winter","Why should bridge surfaces be treated as possible ice first?","They cool from above and below and may freeze before other pavement","They receive more sunlight","They are always heated","Their pavement has extra traction","Exposed bridge decks can freeze even when nearby roads remain wet.","Section 2.12, Winter Driving"),
q("Hazards and conditions","Hot weather","What tire condition needs special attention in very hot weather?","Rising heat and pressure that may contribute to failure","Snow packed in the tread","A frozen valve stem","Lower pressure caused by cold air","Heat builds in tires, especially when they are underinflated or overloaded.","Section 2.13, Driving in Very Hot Weather"),
q("Hazards and conditions","Distracted driving","Why should route information be reviewed before moving?","It reduces the need to read or enter information while driving","It removes the need for road signs","It permits handheld-device use","It shortens braking distance","Planning prevents navigation tasks from taking attention from the roadway.","Section 2.9, Distracted Driving"),

q("Emergencies and fitness","Tire failure","What clue may warn of a tire failure before the vehicle pulls strongly?","A loud bang, vibration, or unusual thumping","A brighter dashboard","A colder engine","A faster air compressor","Noise and vibration can be early signs that a tire has failed.","Section 2.17, Tire Failure"),
q("Emergencies and fitness","Brake failure","What should a driver seek if brakes fade on a steep downgrade?","An escape ramp or other safe escape route","A higher gear and more speed","A place to make a U-turn across traffic","The trailer hand valve alone","Escape routes are designed to stop vehicles whose service brakes cannot control the descent.","Section 2.17, Brake Failure"),
q("Emergencies and fitness","Crash procedures","Why should warning devices be placed promptly after a crash or breakdown?","To prevent approaching traffic from causing another collision","To mark cargo ownership","To replace contacting authorities","To measure stopping distance","Advance warning protects the scene and people providing assistance.","Section 2.20, Accident Procedures"),
q("Emergencies and fitness","Fires","Why should a vehicle fire be approached cautiously with an extinguisher?","Opening a compartment can feed the fire with oxygen","Every fire is harmless outside the cab","Extinguishers work only at close range","Fuel cannot burn after the engine stops","A careful approach limits exposure and avoids suddenly intensifying the fire.","Section 2.21, Fires"),
q("Emergencies and fitness","Fatigue","What should a driver do after noticing repeated lane drift or missed signs?","Stop in a safe place and sleep","Open a window and continue indefinitely","Increase speed to arrive sooner","Rely on caffeine alone","Serious fatigue signals require restorative sleep, not temporary stimulation.","Section 2.23, Staying Alert and Fit to Drive"),
q("Emergencies and fitness","Illness","When should illness or medication keep a driver from operating?","When it can impair alertness, judgment, coordination, or safe control","Only when the vehicle is empty","Only on interstate routes","Never if the driver has a CDL","A commercial driver must be physically and mentally fit for safe operation.","Section 2.23, Staying Alert and Fit to Drive"),
];

const air=[
q("Components","Air compressor","What connects a gear-driven air compressor to the engine?","The engine's gear train","A trailer electrical cable","The service brake pedal","A wheel speed sensor","Some compressors are driven directly through the engine gear system.","Section 5.1, Air Compressor"),
q("Components","Air compressor","Why should a belt-driven compressor belt be inspected?","A loose or damaged belt may prevent adequate air pressure buildup","It controls brake-lining thickness","It releases spring brakes directly","It measures tank pressure","The compressor cannot supply air reliably if its drive belt slips or fails.","Section 5.1, Air Compressor"),
q("Components","Air tanks","What is the purpose of check valves between parts of an air system?","Help prevent air from flowing backward after a failure","Drain every tank automatically","Increase brake-drum diameter","Operate the turn signals","One-way valves help preserve stored air and isolate parts of the system.","Section 5.1, Air Storage Tanks"),
q("Components","Air tanks","Why is moisture especially dangerous in freezing weather?","It can freeze and block valves or lines","It raises tire tread depth","It improves brake cooling","It releases the parking brakes","Frozen moisture can interrupt air flow and brake operation.","Section 5.1, Air Tank Drains"),
q("Components","Brake pedal","Why should the brake pedal not be repeatedly pumped during a normal stop?","Each application can use stored air and reduce system pressure","Pumping increases fuel level","It locks the steering wheel","It disables the compressor permanently","Unnecessary repeated applications waste the finite air stored in the tanks.","Section 5.1, Brake Pedal"),
q("Components","Foundation brakes","What converts air pressure into mechanical force at a wheel?","The brake chamber and linkage","The supply gauge","The safety valve","The air-tank drain","The chamber moves the pushrod and linkage that apply the foundation brake.","Section 5.1, Foundation Brakes"),
q("Components","Foundation brakes","What can excessive brake-drum heat do?","Expand the drum and reduce braking effectiveness","Increase lining friction without limit","Raise air pressure automatically","Tighten every slack adjuster","Heat changes component dimensions and can cause brake fade.","Section 5.1, Foundation Brakes"),
q("Components","Slack adjusters","Who should manually adjust automatic slack adjusters?","A qualified mechanic when repair or adjustment is required","Any driver at every fuel stop","A passenger during travel","No one under any circumstance","Automatic adjusters normally self-adjust; problems require qualified service.","Section 5.1, Slack Adjusters"),
q("Components","Gauges","What does an application-pressure gauge indicate when equipped?","The air pressure being applied to the brakes","The air available in the tires","The compressor belt tension","The trailer cargo weight","Application gauges show how much service-brake pressure the driver is using.","Section 5.1, Application Pressure Gauge"),
q("Components","Warning devices","Why may a wig-wag device drop into view?","To warn that air pressure is too low","To show the tanks are overfilled with fuel","To signal a trailer door is open","To indicate high tire pressure","A wig-wag is one form of required low-air warning.","Section 5.1, Low Air Pressure Warning"),

q("Inspection and tests","Inspection","What should be checked where air hoses connect to brake chambers?","Leaks, damage, and secure fittings","Paint color only","Fuel flow","Tire tread depth","Damaged hoses or loose fittings can cause dangerous air loss.","Section 5.4, Inspecting Air Brake Components"),
q("Inspection and tests","Leak test","Why must air pressure be stabilized before timing a leakage test?","So the measured drop reflects leakage rather than normal system movement","To cool the engine","To engage ABS","To raise the landing gear","A stable starting point makes the leakage measurement meaningful.","Section 5.4, Air Leakage Rate"),
q("Inspection and tests","Low-air test","How is the low-air warning commonly tested?","Fan the service brakes with power on until the warning activates","Drain the fuel tank","Apply the parking brake at highway speed","Disconnect the supply gauge","Reducing pressure through brake applications verifies that the warning activates before the required threshold.","Section 5.4, Low Air Warning Test"),
q("Inspection and tests","Spring-brake test","What should happen as pressure continues to fall during a spring-brake test?","The parking-brake controls should pop out in the specified range","The compressor should stop forever","The service pedal should lock upright","The ABS light should turn green","The pop-out test verifies automatic spring-brake application as pressure becomes unsafe.","Section 5.4, Spring Brake Test"),
q("Inspection and tests","Service-brake test","How should service brakes be checked after moving slowly?","Apply them firmly and note pulling, delay, or unusual feel","Set the parking brakes at full speed","Use only the trailer hand valve","Shift to neutral and coast","A low-speed application reveals uneven or weak braking before road operation.","Section 5.4, Test Service Brakes"),

q("Operation and braking","Normal braking","Why should air-brake applications be smooth and controlled?","Abrupt pressure can lock wheels or destabilize the vehicle","It prevents the compressor from running","It increases the legal load limit","It releases the parking brakes","Progressive braking preserves traction and vehicle balance.","Section 5.3, Normal Stops"),
q("Operation and braking","Downgrades","What is the purpose of releasing the brakes between snub applications?","Allow cooling while the selected low gear controls speed","Drain the tanks completely","Apply the spring brakes","Increase vehicle speed without limit","Intermittent firm applications reduce heat compared with continuous riding.","Section 5.3, Braking on Downgrades"),
q("Operation and braking","Stopping distance","Which air-brake distance is added before the brakes begin slowing the wheels?","Brake-lag distance","Mirror distance","Cargo distance","Coupling distance","Compressed air requires a brief travel time from the valve to the brakes.","Section 5.3, Stopping Distance"),
q("Operation and braking","Emergency braking","With working ABS, how should the driver respond during maximum braking?","Maintain firm brake pressure and steer as needed","Pump the pedal rapidly","Use only the parking brake","Release the pedal whenever ABS activates","ABS automatically controls wheel lock while the driver maintains pressure.","Section 5.3, Emergency Stops"),
q("Operation and braking","Parking","Why should spring brakes not be used if the brakes are extremely hot?","Heat can damage components or make the brakes difficult to release","They will increase tire pressure","They cool the drums instantly","They disengage the transmission","Clamping overheated brakes can cause damage and sticking.","Section 5.3, Parking Brakes"),

q("Low pressure and safety","Low pressure","What is the safest response when the low-air warning activates while driving?","Stop safely as soon as possible and correct the cause","Continue until the spring brakes apply","Pump the pedal repeatedly","Increase engine speed and ignore the warning","Low pressure can soon cause spring-brake application and loss of service braking.","Section 5.1, Low Air Pressure Warning"),
q("Low pressure and safety","Spring brakes","Why should a driver not wait for spring brakes to stop a low-air vehicle?","Automatic application may be sudden and only some wheels may brake","Spring brakes always steer the vehicle","They cannot apply during motion","They increase air pressure first","The driver should make a controlled stop before pressure reaches the automatic-application range.","Section 5.1, Spring Brakes"),
q("Low pressure and safety","Parking brakes","When may wheel chocks be necessary even after parking brakes are applied?","When brake heat, grade, or vehicle condition could allow movement","Only on perfectly level pavement","Only when the engine is running","Never on an air-brake vehicle","Chocks provide added protection when spring brakes may not hold reliably.","Section 5.3, Parking"),
q("Low pressure and safety","Dual systems","What should a driver do if one circuit of a dual air system fails?","Stop safely and have the system repaired","Rely on the remaining circuit for normal service indefinitely","Disconnect the warning light","Drain the working circuit","The remaining circuit offers limited protection, not permission to continue normal operation.","Section 5.2, Dual Air Brake Systems"),
q("Low pressure and safety","Air buildup","Why must normal air pressure be reached before releasing parking brakes?","The service system needs adequate reserve for safe braking","It changes the CDL class","It tests tire inflation","It raises the landing gear","Moving with inadequate reserve risks warnings, weak braking, and automatic spring-brake application.","Section 5.2, Before Driving"),
];

const combination=[
q("Vehicle dynamics","Rollover","Why should a loaded combination enter curves below the posted limit when necessary?","High center of gravity and load movement can make the posted speed unsafe","Trailers cannot follow curves","Posted limits apply only to cars","Lower speed increases rearward amplification","A combination's weight and stability may require a lower safe curve speed.","Section 6.1, Rollover Risks"),
q("Vehicle dynamics","Rearward amplification","What becomes more severe toward the rear of a multi-trailer combination?","Side-to-side movement from quick steering changes","Engine braking","Headlight glare","Fuel consumption only","Steering motion can amplify through each coupling toward the last trailer.","Section 6.1, Steer Gently"),
q("Vehicle dynamics","Braking","Why is early braking important in a combination vehicle?","It reduces the need for hard braking that can cause skids or jackknifes","It releases the fifth wheel","It prevents offtracking","It increases trailer height","Extra time and distance let the combination slow while remaining aligned.","Section 6.1, Brake Early"),
q("Vehicle dynamics","Trailer skid","What should a driver do when a trailer begins skidding from locked brakes?","Release the brakes enough to restore wheel rotation","Apply the trailer hand valve harder","Accelerate sharply","Turn away without reducing braking","Rolling wheels regain side traction and allow the trailer to realign.","Section 6.1, Trailer Skids"),
q("Vehicle dynamics","Jackknife","Why can using the trailer hand valve for normal braking be dangerous?","It may lock trailer wheels and start a jackknife","It applies every tractor brake equally","It improves ABS operation","It raises trailer landing gear","The hand valve can overbrake the trailer and remove its side traction.","Section 6.1, Trailer Hand Valve"),
q("Vehicle dynamics","Offtracking","Where should the driver look while completing a tight turn?","At mirrors to track the trailer wheels and surrounding traffic","Only through the windshield center","At the air-pressure gauge only","At the coupling release handle","Mirror checks confirm that offtracking wheels clear curbs, vehicles, and people.","Section 6.1, Turn Wide"),
q("Vehicle dynamics","Steering","Why should sudden lane changes be avoided with doubles or triples?","Movement becomes amplified toward the last trailer","The engine may stop","The air lines disconnect automatically","The trailers become shorter","Smooth steering prevents whip-like rearward movement and rollover.","Section 6.1, Rollover Risks"),

q("Backing and inspection","Backing","What should the driver do before backing under a trailer?","Line up squarely and confirm the coupling height","Approach at a sharp angle","Raise the trailer above the fifth wheel","Leave the trailer brakes released","A straight, correct-height approach helps the kingpin enter the fifth-wheel jaws properly.","Section 6.2, Coupling"),
q("Backing and inspection","Backing","Why should a driver stop and pull forward after the trailer angle becomes excessive?","Pulling forward can restore control more safely than forcing the backing turn","It locks the trailer brakes","It lowers the landing gear","It removes the need to look","A reset prevents the trailer from jackknifing or striking an unseen object.","Section 6.1, Backing with a Trailer"),
q("Backing and inspection","Inspection","What should be visible when inspecting a properly coupled fifth wheel?","Closed locking jaws around the kingpin shank","A gap between the apron and fifth wheel","The release arm in the unlocked position","Landing gear carrying trailer weight","The jaws must fully surround the kingpin shank and the coupling surfaces must meet.","Section 6.2, Inspecting the Coupling"),
q("Backing and inspection","Inspection","Why inspect the sliding fifth-wheel locking pins?","Unlocked pins can let the fifth wheel move unexpectedly","They control trailer lights","They drain the air tanks","They secure cargo doors","The sliding assembly must be locked on both sides before travel.","Section 6.3, Combination Vehicle Inspection"),
q("Backing and inspection","Inspection","What should be checked along the full length of trailer air and electrical lines?","Secure routing with no cuts, pinching, dragging, or leaks","Matching paint","Warm temperature only","Contact with the catwalk","Protected routing prevents loss of brakes, lights, or electrical power.","Section 6.3, Combination Vehicle Inspection"),

q("Coupling and uncoupling","Coupling","Why should the trailer brakes be locked before coupling?","To keep the trailer from moving during the connection","To raise the trailer nose","To open the fifth-wheel jaws","To drain the tractor tanks","A stationary trailer allows a controlled coupling and tug test.","Section 6.2, Coupling Tractor-Semitrailers"),
q("Coupling and uncoupling","Coupling","What does a coupling tug test confirm?","The fifth-wheel jaws are holding the kingpin","The electrical plug operates every light","The landing gear is fully raised","The cargo is balanced","Gently pulling against locked trailer brakes tests the mechanical connection.","Section 6.2, Coupling Tractor-Semitrailers"),
q("Coupling and uncoupling","Uncoupling","Why should the trailer landing gear contact firm ground before separation?","To support the trailer without sinking or tipping","To release the tractor brakes","To open cargo doors","To test the ABS lamp","Stable support prevents trailer damage or collapse after the tractor moves away.","Section 6.2, Uncoupling Tractor-Semitrailers"),
q("Coupling and uncoupling","Uncoupling","When should the tractor be pulled clear of the trailer?","After lines are disconnected, landing gear is supporting, and the fifth wheel is unlocked","Before lowering landing gear","While air lines remain connected","Before setting trailer brakes","The uncoupling sequence must secure and support the trailer before separation.","Section 6.2, Uncoupling Tractor-Semitrailers"),

q("Air and trailer brakes","Air lines","What can happen if service and emergency air lines are crossed?","Trailer brakes may not operate correctly and spring brakes may release unexpectedly","The trailer lights become brighter","The fifth wheel locks twice","The landing gear raises","Correct glad-hand connections are essential for trailer supply and service-brake control.","Section 6.2, Air and Electric Lines"),
q("Air and trailer brakes","Trailer supply","What does closing the trailer air-supply control do?","Shuts off tractor air to the trailer and applies trailer spring brakes","Applies only tractor steering-axle brakes","Releases trailer parking brakes","Opens the fifth-wheel jaws","The supply control protects tractor air and controls the trailer emergency system.","Section 6.2, Trailer Air Supply Control"),
q("Air and trailer brakes","Protection valve","When should the tractor-protection valve close automatically?","When trailer supply pressure falls into the low-pressure range","At normal governor cut-out","Whenever the turn signal operates","Only when parked on level ground","Automatic closure helps preserve tractor air after a major trailer leak or separation.","Section 6.2, Tractor Protection Valve"),
q("Air and trailer brakes","Trailer brakes","How can trailer service brakes be checked before entering traffic?","Move slowly and apply the trailer hand control gently","Set them at highway speed","Disconnect the emergency line","Use the tractor parking brake only","A low-speed check confirms that the trailer responds before normal road operation.","Section 6.3, Trailer Brake Check"),
];

const passenger=[
q("Inspection and loading","Inspection","What should be checked on every passenger-bus emergency exit?","It opens properly, is marked, and activates any required warning","It is locked permanently","It is hidden by baggage","It opens only from outside","Usable, identified exits are critical for a rapid evacuation.","Section 4.1, Vehicle Inspection"),
q("Inspection and loading","Inspection","Why must aisle and stepwell lighting work?","Passengers need to see walking surfaces during boarding and unloading","It increases engine power","It replaces exterior lights","It changes bus capacity","Adequate lighting reduces slips, falls, and confusion near entrances.","Section 4.1, Vehicle Inspection"),
q("Inspection and loading","Inspection","What should be inspected around a wheelchair lift before use?","Securement, controls, guards, and the clear operating area","Only the paint color","The rear axle ratio","The fuel cap","The lift and surrounding space must be safe before moving a passenger.","Section 4.1, Accessibility Equipment"),
q("Inspection and loading","Boarding","Why should the bus remain secured while passengers board?","Unexpected movement can cause falls or place passengers in traffic","It improves fuel mileage","It releases emergency exits","It raises the standee line","Parking control protects passengers while they are standing near the entrance.","Section 4.2, Loading and Unloading"),
q("Inspection and loading","Boarding","What should a driver do before closing the entrance door?","Check that passengers and belongings are clear of the doorway","Begin moving first","Sound the horn continuously","Turn off interior lights","A final doorway check prevents trapping or striking a passenger.","Section 4.2, Loading and Unloading"),
q("Inspection and loading","Aisles","Why must carry-on items stay out of aisles and exits?","They can block evacuation and cause trips","They increase passenger capacity","They improve weight distribution","They keep doors open","Clear travel paths are necessary during normal movement and emergencies.","Section 4.2, Baggage and Freight"),
q("Inspection and loading","Securement","What should be verified after securing a mobility device?","The device and occupant restraints are attached at approved points","The device can roll freely","Only one rear strap is used","The aisle remains blocked","Correct securement prevents movement and protects the occupant during sudden maneuvers.","Section 4.2, Accessibility"),
q("Inspection and loading","Standee line","When may a passenger stand ahead of the standee line?","Never while the bus is moving","Whenever the bus is below 25 mph","Only on city streets","When every seat is occupied","The area forward of the line must remain clear for visibility and driver control.","Section 4.2, Standee Line"),
q("Inspection and loading","Hazardous materials","What should a bus driver do with a suspicious leaking package?","Do not load it and follow reporting procedures","Place it beneath a passenger seat","Open it to identify the liquid","Carry it in the stepwell","Unknown leaking material may expose passengers to fire, fumes, or contamination.","Section 4.2, Hazardous Materials"),

q("Driving and stops","Curves","Why should a passenger bus take curves smoothly?","Standing or seated passengers can be thrown off balance","It raises the legal speed limit","It improves baggage movement","It eliminates mirror checks","Smooth speed and steering protect occupants who are not restrained like cargo.","Section 4.3, On the Road"),
q("Driving and stops","Stops","What should a driver consider when choosing a passenger stop location?","Traffic exposure, footing, clearance, and a safe path for passengers","Only the shortest route","Fuel price","The color of the curb","A safe stop protects passengers from traffic and fall hazards.","Section 4.3, Bus Stops"),
q("Driving and stops","Driver behavior","When should fare, schedule, or passenger issues be handled?","When the bus is safely stopped","While entering a curve","During a lane change","While crossing railroad tracks","The driver must not divide attention from vehicle control.","Section 4.3, Driver Distractions"),
q("Driving and stops","Prohibited practices","Why should a bus not be towed or pushed with passengers aboard unless necessary for safety?","The maneuver can expose passengers to uncontrolled movement and collision","It improves passenger comfort","It is the normal way to start a bus","It releases emergency exits","Passengers should be removed when feasible before unusual recovery operations.","Section 4.3, Prohibited Practices"),

q("Crossings","Railroad crossings","What should passengers be told to do while the driver listens at railroad tracks?","Remain quiet so the driver can hear an approaching train","Move toward the front door","Open every window","Stand in the aisle","A quiet interior helps the driver detect train sounds and crossing warnings.","Section 4.3, Railroad-highway Crossings"),
q("Crossings","Railroad crossings","Why must the bus have enough space beyond railroad tracks before crossing?","The entire bus must clear the tracks without stopping","The rear axle must remain on the first rail","The bus must shift gears on the tracks","Passengers must unload beyond the rails","A long bus must not become trapped by traffic on the far side.","Section 4.3, Railroad-highway Crossings"),
q("Crossings","Drawbridges","What should a bus driver confirm before crossing a drawbridge without a signal controlling traffic?","The draw is fully closed and safe to cross","The service door is open","Passengers are standing","The parking brake is applied while moving","The driver must stop and verify the movable span is closed unless an exception applies.","Section 4.3, Drawbridges"),
q("Crossings","Railroad crossings","If traffic prevents complete clearance of railroad tracks, what should the bus driver do?","Wait before the tracks until enough space opens","Enter and stop on the tracks","Follow the vehicle ahead closely","Use the opposite lane","The bus must never enter a crossing without room to clear every track.","Section 4.3, Railroad-highway Crossings"),

q("Emergencies","Evacuation","What should the driver take after passengers reach the assembly area?","An accurate passenger count","A fuel receipt","Only the route map","The largest baggage item","Accounting for every passenger is a central part of an evacuation.","Section 4.4, Emergency Procedures"),
q("Emergencies","Breakdown","What should passengers do during a roadside breakdown when remaining aboard is safest?","Follow driver instructions and remain controlled away from exits and traffic","Exit into traffic immediately","Stand around the disabled bus","Walk behind the bus without direction","The safest response depends on location and hazards, with the driver maintaining order.","Section 4.4, Emergency Procedures"),

q("Qualification and rules","Qualification","Why must a passenger-endorsement applicant test in a representative bus?","The skills test must demonstrate safe operation of that passenger-vehicle type","Any passenger car qualifies","The test measures cargo securement only","A written test replaces all vehicle skills","The P endorsement includes vehicle-specific inspection and operating skills.","Section 4, Passenger Vehicles"),
];

const school=[
q("Loading and danger zones","Approach","What should the driver do if students are standing too close as the bus approaches?","Stop short and direct them to a safe waiting position","Continue to the normal stop point","Open the door while moving","Sound the horn and accelerate","The bus must not enter a danger zone occupied by students.","Section 10.2, Approaching the Stop"),
q("Loading and danger zones","Loading","Why should students board one at a time using the handrail?","Orderly boarding reduces falls and pushing near the bus","It increases seating capacity","It keeps warning lights off","It allows the bus to keep moving","Controlled boarding keeps students stable and visible.","Section 10.2, Loading Procedures"),
q("Loading and danger zones","Student crossing","What should a student do after reaching the road edge in front of the bus?","Stop and wait for the driver's signal before entering traffic","Run across without looking","Walk beside the front bumper","Follow another student automatically","A second pause lets the driver make a final traffic check.","Section 10.2, Student Crossing"),
q("Loading and danger zones","Student crossing","Why must the driver watch for a late student approaching the stop?","The student may run into a blind area or traffic","Late students always approach from behind","Warning lights prevent every risk","The bus can move while the student boards","Unexpected movement around the bus demands continued mirror and traffic checks.","Section 10.2, Loading and Unloading"),
q("Loading and danger zones","Dropped objects","Why must the bus remain stopped when a child reports a dropped item?","The child may enter a danger zone to retrieve it","The item changes axle weight","The mirrors stop working","The warning lights need cooling","The driver must locate the child and control retrieval before moving.","Section 10.2, Loading and Unloading"),
q("Loading and danger zones","Unloading","What should students be reminded to do after crossing in front of the bus?","Continue to a safe location away from the roadway and bus","Return to the service door","Walk alongside the bus","Stop beside the rear wheels","Students should promptly clear every danger zone.","Section 10.2, Unloading Procedures"),
q("Loading and danger zones","Counting students","When is the student count complete after unloading?","When every student is located and safely clear of the bus","When the door closes","When the warning lights turn off","When traffic begins moving","The driver must account for each child before releasing brakes.","Section 10.2, Unloading Procedures"),
q("Loading and danger zones","Backing","Why should a school bus route be planned to avoid backing?","Children and objects can disappear into large blind zones","Backing improves mirror coverage","Students are safer behind the bus","Backing reduces route time in every case","Avoiding the maneuver removes a major danger-zone risk.","Section 10.2, Special Dangers"),
q("Loading and danger zones","Backing","If a spotter is lost from view while backing, what should the driver do?","Stop immediately","Continue slowly","Turn away from the spotter","Sound the horn and accelerate","The driver must stop whenever visual communication with the spotter is lost.","Section 10.2, Backing"),

q("Mirrors","Mirror use","What should be visible in properly adjusted crossover mirrors?","The front danger zone from the bumper outward","Only traffic far behind","The bus roof","Only the entrance steps","Crossover mirrors reveal children and objects close to the front corners.","Section 10.1, Correct Mirror Adjustment"),
q("Mirrors","Mirror use","Why should mirror adjustment be checked before the route begins?","A moved mirror can leave dangerous blind areas around the bus","Mirrors control warning lamps","It changes the bus capacity","It replaces the pre-trip inspection","Correct coverage is essential before students enter danger zones.","Section 10.1, Danger Zones and Mirrors"),

q("Crossings","Railroad crossings","Why should the school bus stop with enough distance from the nearest rail?","To see and listen without placing any part of the bus in the train path","To let students leave the bus","To shift gears on the rail","To block following traffic on the tracks","The required stopping position provides a safe observation point.","Section 10.3, Railroad-highway Crossings"),
q("Crossings","Railroad crossings","What should the driver verify on the far side before crossing?","Enough room exists for the entire bus beyond the tracks","The route is on time","The rear door is open","Students are standing","Traffic must not trap any part of the bus on the crossing.","Section 10.3, Railroad-highway Crossings"),
q("Crossings","Railroad crossings","Why should the bus cross railroad tracks in a gear that needs no shifting?","A missed shift could stall the bus on the tracks","Shifting activates warning lights","The doors lock during shifts","The train signal changes with engine speed","Selecting the gear beforehand prevents loss of power while exposed.","Section 10.3, Railroad-highway Crossings"),

q("Emergencies","Evacuation","When may moving students off the bus create more danger than keeping them aboard?","When traffic, weather, or outside hazards are worse than the condition inside","Whenever the route is late","Whenever students are noisy","When the interior lights work","The driver must compare immediate hazards before ordering an evacuation.","Section 10.4, Emergency Evacuation"),
q("Emergencies","Evacuation","Why should evacuation helpers know their assignments before an emergency?","Prepared roles speed movement and student accountability","They replace the driver","They may direct traffic from the roadway","They decide whether to call for help","Practice reduces confusion and supports an orderly evacuation.","Section 10.4, Evacuation Planning"),

q("Operations and students","Student management","What should the driver explain before the route about behavior expectations?","Rules that keep aisles, exits, and driver attention clear","How to distract the driver","How to open exits while moving","Where to stand ahead of the line","Clear expectations prevent conduct that interferes with safe operation.","Section 10.5, Student Management"),
q("Operations and students","Post-trip","What should be checked after the last student leaves besides the seats?","Floor, under seats, restrooms if equipped, and every rear area","Only the dashboard clock","Only the exterior mirrors","Only the fuel gauge","A deliberate sweep covers places where a child or dangerous item could remain hidden.","Pupil Transportation Guide, Post-trip Check"),
q("Operations and students","Nebraska operations","Why must the bus capacity rating never be exceeded?","Every student needs an intended seating position and vehicle limits must be respected","Standing students improve balance","Capacity applies only off public roads","Extra riders reduce stopping distance","Safe seating and rated weight limits protect occupants and vehicle control.","Pupil Transportation Guide, Seating"),
q("Operations and students","Nebraska operations","What should a Nebraska pupil transportation driver do with a defect found during the pre-trip inspection?","Report it promptly in writing and keep an unsafe vehicle out of service","Ignore it until the 80-day inspection","Ask students to monitor it","Erase it from the form","The guide requires documentation and correction of safety-related deficiencies.","Pupil Transportation Guide, Inspection Process"),
];

export const thirdRows={general,air,combination,passenger,school};

