const q = (domain, topic, prompt, correct, wrong1, wrong2, wrong3, explanation, source) => [domain, topic, prompt, correct, wrong1, wrong2, wrong3, explanation, source];

const general = [
  q("Licensing and rules","License classes","With the proper endorsements, what may a Nebraska Class A CDL holder also drive?","Class B and Class C commercial vehicles","Only Class A combinations","Class B vehicles but never Class C","Only noncommercial vehicles","Class A includes the lower commercial classes when the required endorsements are present.","Nebraska Specifics, CDL Classes"),
  q("Licensing and rules","License classes","With the proper endorsement, a Class B CDL holder may also operate which class?","Class C","Class A","Motorcycle only","No other class","Nebraska authorizes Class B holders to operate Class C vehicles when properly endorsed.","Nebraska Specifics, CDL Classes"),
  q("Licensing and rules","License classes","What noncommercial privilege is included with a valid Nebraska CDL?","Class O vehicles other than motorcycles","Every motorcycle","Farm vehicles only","No noncommercial vehicle","A valid CDL also authorizes Class O operation, excluding motorcycles.","Nebraska Specifics, CDL Classes"),
  q("Licensing and rules","Eligibility","What is Nebraska's minimum age for intrastate CDL operation?","18","16","20","21","Nebraska permits intrastate CDL operation at age 18.","Nebraska Specifics, Minimum Age"),
  q("Licensing and rules","Testing","Which written test is normally required again when transferring or renewing a HazMat endorsement?","Hazardous materials","General knowledge","Air brakes","Combination vehicles","HazMat knowledge testing is the written-test exception described for transfers and renewals.","Nebraska Specifics, Testing"),
  q("Licensing and rules","Testing","After failing a Nebraska CDL written or skills test, what is the minimum wait before retesting?","At least one day","One hour","Seven days","Thirty days","Nebraska requires at least a one-day wait after a failed written or skills test.","Nebraska Specifics, Testing"),
  q("Licensing and rules","Learner permit","Who must accompany a driver practicing with a CLP?","A properly licensed CDL holder","Any adult passenger","A learner with the same permit","No one if the vehicle is empty","A CLP authorizes supervised practice with a qualified CDL holder.","Nebraska Specifics, Commercial Learner's Permit"),
  q("Licensing and rules","Learner permit","What must an applicant pass before a CLP can be issued?","All applicable knowledge tests","Only the vision test","The road test","Only General Knowledge regardless of vehicle","The permit class and endorsements determine which knowledge tests apply.","Nebraska Specifics, Commercial Learner's Permit"),
  q("Licensing and rules","Restrictions","A driver tests in an automatic-transmission CMV. Which restriction is normally added?","E","L","K","O","The E restriction prohibits manual-transmission-equipped CMVs.","Nebraska Specifics, CDL Restrictions"),
  q("Licensing and rules","Restrictions","Which restriction identifies intrastate-only commercial driving?","K","V","Z","N","K is the intrastate-only restriction.","Nebraska Specifics, CDL Restrictions"),
  q("Licensing and rules","Documents","May a post-office box serve as Nebraska principal-address proof?","No","Yes, by itself","Yes, with no other document","Only for applicants under 21","Nebraska requires a physical principal address, not a P.O. box.","Nebraska Specifics, Principal Address"),
  q("Licensing and rules","Documents","What must be disclosed when applying for a Nebraska CDL or CLP?","A valid Social Security number","Every former employer","A personal credit score","A vehicle purchase price","Applicants must disclose their valid Social Security number.","Nebraska Specifics, Application Documents"),

  q("Inspection and cargo","Inspection","What should tire inspection include?","Inflation, condition, and adequate tread","Paint color and brand only","Wheelbase measurement only","Fuel mileage","Unsafe tires can fail from low pressure, damage, or insufficient tread.","Section 2.1, Vehicle Inspection"),
  q("Inspection and cargo","Inspection","What should be checked on lights and reflectors before a trip?","They are clean, the correct color, and working","They match the cab paint","They stay off in rain","Only the interior dome light works","Visibility equipment must be clean, correctly colored, and operational.","Section 2.1, Vehicle Inspection"),
  q("Inspection and cargo","Cargo","After the first cargo check, when should securement be rechecked?","After 3 hours or 150 miles and after duty changes","Only at the destination","Every 1,000 miles","Only if cargo is visible in a mirror","Periodic checks catch shifting or loosened securement.","Section 3.1, Inspecting Cargo"),
  q("Inspection and cargo","Cargo","Why must axle-weight limits be observed?","Excess axle weight can damage components and reduce control","They apply only to empty vehicles","They improve acceleration","They replace gross-weight limits","Weight must be legal and safely distributed across axles.","Section 3.2, Weight and Balance"),
  q("Inspection and cargo","Cargo","What is the safest position for the heaviest cargo?","As low and centered as practical","High and against one side","At the extreme rear","On top of lighter cargo","Low, centered weight improves stability and axle balance.","Section 3.2, Weight and Balance"),
  q("Inspection and cargo","Cargo","Why may some cargo require a cover?","To protect people from falling or blowing cargo","To replace all tiedowns","To increase the weight rating","To hide damaged freight","Covers help contain loose material but do not replace securement.","Section 3.3, Securing Cargo"),
  q("Inspection and cargo","Cargo","What should a driver do with a damaged tiedown?","Replace it before relying on it","Use it only on the heaviest item","Tie it to another damaged tiedown","Ignore it if the trip is short","Securement devices must be in proper working condition.","Section 3.3, Securing Cargo"),
  q("Inspection and cargo","Cargo","What must doors, tailgates, and other cargo equipment do before travel?","Close and secure properly","Remain partly open for ventilation","Be held by cargo weight","Open automatically in turns","Cargo openings must be secured so freight cannot escape.","Section 3.3, Securing Cargo"),

  q("Driving and control","Space management","A 40-foot vehicle traveling under 40 mph needs at least what following time?","Four seconds","One second","Two seconds","Eight seconds","Use one second for every 10 feet of vehicle length below 40 mph.","Section 2.7, Following Distance"),
  q("Driving and control","Space management","What adjustment is added to following distance above 40 mph?","At least one additional second","Subtract one second","No adjustment","Double speed instead","The manual adds a second at higher speeds because stopping distance grows.","Section 2.7, Following Distance"),
  q("Driving and control","Speed","How fast should you drive when you cannot stop within the distance you can see?","Slow enough to stop within the visible distance","At the posted maximum","Faster than surrounding traffic","At least 55 mph","Speed must match sight distance, especially at night or in bad weather.","Section 2.6, Controlling Speed"),
  q("Driving and control","Weather","What is the best response if the vehicle begins hydroplaning?","Ease off the accelerator and avoid hard braking","Brake hard immediately","Turn sharply","Accelerate to regain tire contact","Gentle slowing helps tires regain contact without triggering a skid.","Section 2.12, Wet Roads"),
  q("Driving and control","Mountain driving","What should a driver do if brakes fail on a downgrade and an escape ramp is available?","Use the escape ramp","Continue to the bottom","Turn uphill across traffic","Apply only the trailer hand valve","Escape ramps are designed to stop runaway vehicles.","Section 2.16, Escape Ramps"),
  q("Driving and control","Communication","When changing lanes, how long should the turn signal remain on?","Until the lane change is complete","Only for one flash","Until the front wheels cross the line","It is unnecessary with mirrors","Continuous signaling clearly communicates the whole maneuver.","Section 2.5, Signaling"),
  q("Driving and control","Communication","When is the horn most appropriate?","When needed to warn someone of danger","At every intersection","To express frustration","Continuously in heavy traffic","The horn is a warning device, not a substitute for space or patience.","Section 2.5, Communicating Presence"),
  q("Driving and control","Space management","Why avoid driving beside another vehicle for long periods?","It can trap the CMV with no escape route","It always saves fuel","It shortens stopping distance","It improves mirror coverage","Open space beside the vehicle provides room for emergency movement.","Section 2.7, Space to the Sides"),
  q("Driving and control","Speed","When should most braking for a curve occur?","Before entering the curve","At the sharpest point","After leaving the curve","Only if the trailer sways","Entering at a controlled speed prevents skids and rollover.","Section 2.6, Curves"),
  q("Driving and control","Railroad crossings","What should be considered before crossing tracks with a long or low vehicle?","Whether there is enough clearance to cross completely","Only the train's color","The radio volume","Whether another truck crossed yesterday","Long or low-clearance vehicles can become trapped on a crossing.","Section 2.15, Railroad Crossings"),
  q("Driving and control","Mountain driving","Why is a lower gear selected before descending?","To let engine braking help control speed","To reduce mirror vibration","To release the service brakes","To raise the center of gravity","Engine braking reduces service-brake heat buildup.","Section 2.16, Mountain Driving"),
  q("Driving and control","ABS","During an emergency stop with ABS, how should the brake pedal generally be used?","Apply firm pressure and keep it applied","Pump it rapidly","Release it completely","Use the parking brake instead","ABS controls wheel lockup while the driver maintains braking pressure.","Section 2.18, ABS"),
  q("Driving and control","Skids","What should you do when drive wheels begin a braking skid?","Release the brake to regain traction","Apply more brake","Accelerate hard","Set the parking brake","Locked wheels need to roll again before steering control can return.","Section 2.19, Drive-wheel Skids"),
  q("Driving and control","Backing","What does G.O.A.L. remind a driver to do?","Get Out And Look","Go Over All Lanes","Gauge Overall Axle Load","Give Others A Light","Getting out to inspect the path is safer than guessing through blind spots.","Section 2.2, Backing Safely"),
  q("Driving and control","Turning","Why may a large vehicle need extra room for a right turn?","Rear wheels track inside the front-wheel path","The steering wheel locks right","Air pressure falls in every turn","The vehicle becomes shorter","Offtracking can send rear wheels over a curb or into nearby objects.","Section 2.7, Turns"),
  q("Driving and control","Space management","Before merging, what space must be considered?","The vehicle's length, acceleration, and traffic gap","Only the posted speed","Only traffic ahead","The cargo's color","Large vehicles need more time and distance to enter traffic safely.","Section 2.7, Space to Merge"),
  q("Driving and control","Clearance","Why should overhead clearance be checked instead of assumed?","Road grades, snow, and cargo height can change actual clearance","Every bridge sign is intentionally low","Air brakes raise the trailer","Mirrors measure height automatically","Vehicle and roadway conditions may reduce the available space.","Section 2.7, Space Overhead"),

  q("Hazards and conditions","Work zones","What is the safest work-zone approach?","Slow early, increase space, and obey workers and signs","Maintain speed to leave quickly","Follow equipment closely","Change lanes repeatedly","Work zones contain narrow lanes, people, and sudden traffic changes.","Section 2.8, Work Zones"),
  q("Hazards and conditions","Fog","Which headlights are best in fog?","Low beams","High beams","Parking lights only","No lights","High beams reflect from fog and reduce visibility.","Section 2.11, Fog"),
  q("Hazards and conditions","Hot weather","What should be done if a tire is too hot to touch safely?","Stop and let it cool","Release air immediately","Pour cold water on it","Drive faster for airflow","An overheated tire may fail; removing air can make the pressure unsafe.","Section 2.13, Hot Weather"),
  q("Hazards and conditions","Winter","Which roadway surfaces often freeze before the rest of the road?","Bridges and shaded areas","Dry tunnels","Freshly painted lines only","Gravel shoulders only","Exposed and shaded surfaces can freeze even when other pavement appears clear.","Section 2.12, Winter Driving"),
  q("Hazards and conditions","Wet brakes","After driving through deep water, how can brakes be dried?","Apply light pressure while moving slowly until they work normally","Set the parking brakes at highway speed","Pump the accelerator","Shift to neutral and coast","Gentle application creates heat and confirms braking has returned.","Section 2.12, Wet Brakes"),
  q("Hazards and conditions","Distracted driving","What should happen to a handheld device before driving?","Secure it and handle necessary tasks while safely parked","Hold it below the window","Place it on the steering wheel","Use it only in curves","Preventing device use removes a major source of distraction.","Section 2.9, Distracted Driving"),
  q("Hazards and conditions","Aggressive driving","What should you do when another driver cuts in closely?","Restore following distance without retaliating","Sound the horn continuously","Tailgate the vehicle","Race to pass immediately","Calmly rebuilding space is safer than escalating the conflict.","Section 2.10, Aggressive Drivers"),

  q("Emergencies and fitness","Fires","What is an early response to an engine fire?","Stop safely and shut off the engine","Open the hood fully at once","Keep driving for airflow","Pour fuel on the engine","Stopping the engine can remove fuel or power feeding the fire.","Section 2.21, Fires"),
  q("Emergencies and fitness","Fires","Why must the extinguisher rating match the fire?","The wrong agent can spread danger or fail to extinguish it","Every extinguisher works on every fire","Ratings apply only to color","A rating measures tire pressure","Fire classes require suitable extinguishing agents.","Section 2.21, Fires"),
  q("Emergencies and fitness","Crash procedures","After protecting a crash scene, what should the driver do?","Notify authorities and assist without creating more danger","Leave immediately","Move every injured person","Remove warning devices","Prompt reporting and careful assistance are part of crash responsibilities.","Section 2.20, Accident Procedures"),
  q("Emergencies and fitness","Fatigue","Which is a warning sign of dangerous fatigue?","Frequent yawning and difficulty keeping eyes open","Steady lane position","Normal alert scanning","Comfortable posture","Fatigue signs mean the driver should stop and sleep.","Section 2.23, Fatigue"),
  q("Emergencies and fitness","Fitness","What should a driver verify before using medicine?","It is safe for commercial driving and will not impair alertness","It tastes sweet","It is sold without a prescription","Another driver has used it","Prescription and nonprescription drugs can still make driving unsafe.","Section 2.23, Medicines"),
  q("Emergencies and fitness","Alcohol","What happens to a CMV driver's judgment before obvious signs of drunkenness appear?","It can already be impaired","It always improves","It is unaffected below 0.08 percent","It changes only after sleep","Alcohol reduces judgment and coordination before a person appears intoxicated.","Section 2.22, Alcohol"),
];

const air = [
  q("Components","Air compressor","What drives the air compressor on most commercial vehicles?","The engine through gears or a belt","The trailer wheels","The battery alone","The service brake pedal","The engine supplies the mechanical power needed to compress air.","Section 5.1, Air Compressor"),
  q("Components","Air compressor","When pressure falls to the governor cut-in level, what should happen?","The compressor begins pumping again","The safety valve opens","The spring brakes apply","The tanks drain automatically","Cut-in pressure tells the governor to rebuild the air supply.","Section 5.1, Governor"),
  q("Components","Air tanks","Why can water in an air tank be dangerous in freezing weather?","It can freeze and block brake-system parts","It increases tire tread","It improves lubrication","It raises fuel pressure","Frozen moisture can prevent valves and lines from operating.","Section 5.1, Air Tank Drains"),
  q("Components","Check valve","What is the purpose of a one-way check valve?","Allow air to flow in one direction and prevent backflow","Measure brake-lining thickness","Release the parking brakes","Cool the compressor","Check valves help preserve stored air if another part of the system leaks.","Section 5.1, Air Brake Components"),
  q("Components","Brake drums","What can grease or oil on brake linings cause?","Reduced braking friction","Higher air pressure","Faster compressor recovery","Better heat removal","Contaminated friction surfaces may not stop the vehicle effectively.","Section 5.1, Foundation Brakes"),
  q("Components","Brake drums","Why are cracked brake drums unsafe?","They may fail or reduce braking","They improve cooling","They increase lining contact","They prevent brake fade","Cracks can weaken the drum and interfere with normal braking.","Section 5.1, Foundation Brakes"),
  q("Components","Slack adjusters","Who should adjust automatic slack adjusters when they are outside limits?","A qualified mechanic","Any passenger","The driver while moving","A fuel attendant","Frequent manual adjustment can hide a mechanical defect and requires qualified repair.","Section 5.1, Slack Adjusters"),
  q("Components","Application gauge","What may an application-pressure gauge indicate?","The air pressure being applied to the brakes","Fuel pressure","Trailer height","Tire inflation","High application pressure for the same stop can warn of fading or adjustment problems.","Section 5.1, Application Pressure Gauge"),
  q("Components","Brake lights","What activates air-brake stop lights?","An air-pressure switch when service brakes are applied","The air-tank drain","The governor cut-out","The trailer landing gear","The electrical stop-light switch responds to brake application pressure.","Section 5.1, Stop-light Switch"),
  q("Components","Wig-wag","What is a wig-wag in an air-brake vehicle?","A mechanical low-air warning device","A type of brake drum","A coupling lock","A tire-pressure gauge","Some vehicles use a visible mechanical arm to warn of low air pressure.","Section 5.1, Low-air Warning"),

  q("Inspection and tests","Build-up test","What does the air-pressure build-up test measure?","How quickly system pressure rises","How quickly tires inflate","Brake-drum temperature","Trailer cargo weight","Slow pressure build-up may indicate compressor or system problems.","Section 5.4, Air-pressure Build-up"),
  q("Inspection and tests","Build-up test","When checking pressure build-up, the engine is normally operated at what speed?","The manufacturer-specified fast idle","With the engine shut off","Maximum governed speed","Idle with all tanks open","The test uses the specified engine speed and pressure range.","Section 5.4, Air-pressure Build-up"),
  q("Inspection and tests","Low-air test","How is the low-air warning commonly tested?","Reduce pressure with brake applications until the warning activates","Add air above cut-out","Disconnect the gauge","Drive at highway speed","Controlled pressure reduction verifies the warning appears before unsafe pressure.","Section 5.4, Low-air Warning Test"),
  q("Inspection and tests","Spring-brake test","How can automatic spring-brake application be checked while parked?","Reduce air pressure and observe when the controls pop out","Raise pressure above 150 psi","Release all brakes and drive","Disconnect the compressor belt","The parking controls should activate in the manufacturer's low-pressure range.","Section 5.4, Spring-brake Test"),
  q("Inspection and tests","Service-brake test","How should service brakes be checked before entering traffic?","Move slowly and apply them to check stopping and pulling","Test them first at highway speed","Use only the parking brake","Check them with the engine off and vehicle parked","A low-speed application reveals delayed stopping or pulling to one side.","Section 5.4, Service-brake Test"),

  q("Operation and braking","Normal braking","Why should the brake pedal not be pumped during normal air-brake stops?","Repeated applications can waste stored air","It raises fuel pressure","It locks the steering wheel","It fills the tanks faster","Each application and release can reduce available air pressure.","Section 5.3, Normal Stops"),
  q("Operation and braking","Emergency braking","What is stab braking?","Fully apply brakes, release when wheels lock, then reapply after wheels roll","Hold light pressure continuously","Use only spring brakes","Pump the accelerator","Stab braking is a non-ABS emergency method that restores rolling traction between applications.","Section 5.3, Emergency Stops"),
  q("Operation and braking","Grades","Why is riding the brakes on a downgrade unsafe?","It creates heat that can cause fade or failure","It increases tank pressure","It cools the drums too quickly","It improves stopping power indefinitely","Continuous light pressure can overheat braking surfaces.","Section 5.3, Downgrades"),
  q("Operation and braking","Parking","Why should the brake pedal be released after stopping on a level road when checking parking brakes?","To confirm the spring brakes alone hold the vehicle","To drain all tanks","To test the horn","To raise compressor pressure","A parking-brake test isolates whether the parking system can hold.","Section 5.4, Parking-brake Test"),
  q("Operation and braking","Low traction","On a slippery road, what braking input is safest?","Gentle, controlled pressure that avoids wheel lock","Full spring-brake application","Rapid steering with hard braking","Trailer hand valve only","Smooth braking preserves traction and directional control.","Section 5.3, Low Traction"),

  q("Low pressure and safety","Emergency line","If air pressure becomes very low while driving, what should you do?","Stop safely before spring brakes apply automatically","Increase speed","Keep driving until pressure reaches zero","Hold the parking control in","Very low pressure can trigger sudden spring-brake application.","Section 5.3, Low Air Pressure"),
  q("Low pressure and safety","Spring brakes","Why are spring brakes powerful?","Strong mechanical springs apply them without service air","They use engine coolant","They depend on battery power","They use tire pressure","The springs provide parking and emergency braking when air is absent.","Section 5.1, Spring Brakes"),
  q("Low pressure and safety","Parking brakes","Why should spring brakes not be applied while moving normally?","They can cause loss of control or brake damage","They improve steering","They recharge the air tanks","They cool the drums","Spring brakes are intended for parking and emergency situations.","Section 5.1, Parking Brakes"),
  q("Low pressure and safety","Dual systems","If one dual-air circuit loses pressure, what should the driver expect?","A warning and reduced braking capacity","Both circuits always remain perfect","The engine shuts off instantly","The trailer uncouples","The remaining circuit may provide braking, but the vehicle must be stopped safely.","Section 5.2, Dual Air Systems"),
  q("Low pressure and safety","Supply pressure","Why must full operating pressure be reached before moving?","Low pressure may leave inadequate service and emergency braking","It changes the CDL class","It unlocks the fifth wheel","It increases tire tread","Both air circuits need an adequate reserve for safe operation.","Section 5.2, Before Driving"),
];

const combination = [
  q("Vehicle dynamics","Rollover","What driving behavior most directly reduces combination-vehicle rollover risk?","Enter curves slowly and steer smoothly","Brake hard halfway through curves","Make quick lane changes","Load all freight high","Speed and abrupt steering are leading controllable rollover factors.","Section 6.1, Rollover"),
  q("Vehicle dynamics","Rollover","Why does an empty trailer sometimes handle poorly?","Its light weight can reduce traction and increase bounce","It has a lower legal speed in every state","Its brakes cannot work","It cannot offtrack","Empty trailers may have less tire grip and can bounce on rough roads.","Section 6.1, Empty Trailers"),
  q("Vehicle dynamics","Braking","What helps prevent a jackknife during a stop?","Brake early and keep tractor and trailer wheels rolling","Use the trailer hand valve alone","Steer sharply while braking","Accelerate through the stop","Balanced, controlled braking preserves traction throughout the combination.","Section 6.1, Prevent Trailer Skids"),
  q("Vehicle dynamics","Trailer skid","What is the first sign a trailer may be skidding?","It appears in a mirror to move out of line","The air gauge rises","The landing gear lowers","The fifth wheel moves forward","Mirror checks can reveal sideways trailer movement before the driver feels it.","Section 6.1, Trailer Skids"),
  q("Vehicle dynamics","Offtracking","Which part of a long combination cuts closest to the inside of a turn?","The rear wheels of the last trailer","The tractor's front bumper","The outside mirror","The steering axle","Rear wheels follow a shorter inside path and need clearance.","Section 6.1, Offtracking"),
  q("Vehicle dynamics","Following distance","Why does an empty combination still require generous following distance?","Empty vehicles can have reduced traction and difficult braking","Empty trailers stop instantly","Air brakes do not work empty","The tractor becomes shorter","Less weight over the tires can make wheel lockup more likely.","Section 6.1, Following Distance"),
  q("Vehicle dynamics","Railroad crossings","What must a combination driver know before crossing raised tracks?","The vehicle has enough underside clearance","The trailer doors are open","The service line is disconnected","The landing gear touches the road","Low-slung units can become stuck on a humped crossing.","Section 6.1, Railroad Crossings"),

  q("Backing and inspection","Backing","When the trailer drifts right while backing, which way is the top of the steering wheel initially moved?","Right to bring the trailer left","Left to move the trailer farther right","Straight ahead only","The wheel is not used","Steering corrections are made opposite the trailer's desired movement when using the wheel top as reference.","Section 6.1, Backing"),
  q("Backing and inspection","Backing","Why should a helper remain visible while backing?","The driver must stop if visual contact is lost","The helper controls the brakes","The helper replaces mirror use","The helper may stand behind the trailer","Losing sight of the helper means the movement is no longer safely directed.","Section 6.1, Backing"),
  q("Backing and inspection","Inspection","What should be checked between the upper and lower fifth-wheel surfaces?","There is no visible gap","A two-inch gap remains","Grease is completely absent","The kingpin head is above the jaws","No gap indicates the trailer apron is seated on the fifth wheel.","Section 6.2, Coupling Inspection"),
  q("Backing and inspection","Inspection","What should be checked on sliding fifth-wheel locking pins?","They are fully engaged and none are missing","They are removed for turns","They touch the tires","They move freely while driving","Engaged pins keep the fifth wheel from sliding unexpectedly.","Section 6.5, Combination Inspection"),
  q("Backing and inspection","Inspection","What must landing gear look like before travel?","Fully raised with the crank secured","Partly lowered for balance","Touching the pavement","Held up by air lines","Raised, secured gear prevents road contact and damage.","Section 6.5, Combination Inspection"),

  q("Coupling and uncoupling","Coupling","Before backing under a trailer, why should the trailer brakes be locked?","To prevent the trailer from moving during coupling","To drain tractor air","To raise the trailer","To unlock the fifth wheel","A stationary trailer allows the kingpin and fifth wheel to connect safely.","Section 6.2, Coupling"),
  q("Coupling and uncoupling","Coupling","What should the tractor do as it first contacts a properly positioned trailer?","Lift the trailer slightly","Push the trailer several feet","Lower the landing gear","Disconnect the electrical cable","Slight lifting confirms suitable height and firm apron contact.","Section 6.2, Couple Tractor and Semitrailer"),
  q("Coupling and uncoupling","Uncoupling","Why is the trailer suspension allowed to settle after landing gear contacts the ground?","To remove weight from the tractor without lifting the trailer excessively","To drain the air tanks","To lock the service line","To cool the brakes","Proper weight transfer protects the landing gear and fifth wheel.","Section 6.3, Uncoupling"),
  q("Coupling and uncoupling","Uncoupling","After unlocking the fifth wheel, how should the tractor first move?","Pull partly clear, stop, and verify the trailer is supported","Drive completely away at speed","Turn sharply under the trailer","Release the trailer brakes","A partial pullout lets the driver catch a support problem before separation.","Section 6.3, Uncoupling"),

  q("Air and trailer brakes","Air lines","What can happen if the service and emergency air lines are crossed?","Trailer brakes may not work correctly and tanks may not charge","The trailer lights become brighter","The fifth wheel locks twice","The landing gear rises","Correct red and blue connections are essential to supply and control air.","Section 6.4, Trailer Air Lines"),
  q("Air and trailer brakes","Air lines","What should glad-hand rubber seals be checked for?","Damage, missing seals, and leaks","Paint color only","Cargo weight","Electrical voltage","Good seals prevent air loss at trailer connections.","Section 6.4, Glad Hands"),
  q("Air and trailer brakes","Trailer hand valve","Why should the trailer hand valve not be used for parking?","Air can leak away and release the trailer brakes","It applies the tractor brakes too strongly","It raises the landing gear","It cannot apply trailer brakes","Spring parking brakes or wheel chocks provide secure parking.","Section 6.4, Trailer Hand Valve"),
  q("Air and trailer brakes","Tractor protection","When does the tractor-protection valve normally close?","When trailer air pressure becomes dangerously low","At normal cut-out pressure","Whenever headlights turn on","Only while backing","Closing protects the tractor's remaining air after a severe trailer leak or separation.","Section 6.4, Tractor-protection Valve"),
];

const passenger = [
  q("Inspection and loading","Inspection","What should be checked on a bus floor before carrying passengers?","It is strong, clear, and free of hazards","It is covered by baggage","It slopes toward an exit","It has loose panels","A clear, sound floor reduces trips and supports safe evacuation.","Section 4.1, Passenger-vehicle Inspection"),
  q("Inspection and loading","Inspection","What should be checked on emergency-exit warning devices?","They operate when an exit is opened","They remain disconnected","They work only with the engine off","They sound whenever the service door opens","Exit warnings alert the driver to an unsecured emergency opening.","Section 4.1, Emergency Equipment"),
  q("Inspection and loading","Inspection","Why inspect seat frames and cushions?","Loose or damaged seats can injure passengers","They determine CDL class","They control air pressure","They replace occupant restraints","Passenger seating must be securely attached and safe.","Section 4.1, Seats"),
  q("Inspection and loading","Loading","How should baggage be secured?","So it cannot shift, fall, or block an exit","Only by stacking it high","Against the emergency door","In the driver's footwell","Secure baggage protects occupants during sudden movement.","Section 4.2, Baggage and Freight"),
  q("Inspection and loading","Loading","Where should hazardous material allowed on a bus be carried?","Only as permitted and never where it endangers passengers","In an open container","Beside the driver","Blocking a rear exit","Passenger carriers face strict type, quantity, and placement limits.","Section 4.2, Hazardous Materials"),
  q("Inspection and loading","Boarding","What should the driver do if passengers are still moving to seats?","Wait until they are safely positioned before moving","Accelerate gently","Close the door on the aisle","Ask them to hold baggage overhead","Starting only when passengers are stable prevents falls.","Section 4.2, Loading"),
  q("Inspection and loading","Aisles","May baggage occupy an aisle temporarily during travel?","No","Yes, below 25 mph","Yes, if it is soft","Only at night","Aisles and exits must remain unobstructed throughout the trip.","Section 4.2, Baggage and Freight"),
  q("Inspection and loading","Standee line","Why must standing passengers remain behind the standee line?","To preserve the driver's view and access to controls","To balance rear tire pressure","To keep the rear exit locked","To improve radio reception","People forward of the line can obstruct safe vehicle operation.","Section 4.2, Standee Line"),
  q("Inspection and loading","Securement","Before moving a lift-equipped bus, what must be confirmed?","The lift is secured and its door is closed","The lift is partly extended","The lift alarm is disconnected","A passenger stands on the lift","A stowed, secured lift prevents movement and door hazards.","Section 4.1, Lift-equipped Vehicles"),

  q("Driving and stops","Stops","How should a bus leave a curbside stop?","Signal, check mirrors, and wait for a safe gap","Pull out before signaling","Rely on passengers to watch traffic","Back into the traffic lane","Communication and a full mirror scan protect passengers and road users.","Section 4.3, Bus Stops"),
  q("Driving and stops","Braking","Why should bus stops be smooth and gradual?","Sudden braking can throw or injure passengers","Air brakes work only gradually","It reduces legal passenger capacity","It opens emergency exits","Passenger vehicles demand extra care because occupants may be standing or unbelted.","Section 4.3, Safe Driving"),
  q("Driving and stops","Curves","Why may a posted curve speed still be too fast for a bus?","The bus's size, load, and conditions may require a lower speed","Buses may ignore curve signs","Passenger weight improves every turn","The speed applies only to trucks","Posted guidance does not account for every vehicle and condition.","Section 4.3, Curves"),
  q("Driving and stops","Fueling","What should a bus driver do before fueling?","Follow carrier rules, shut down as required, and control ignition sources","Leave the engine racing","Allow smoking nearby","Block an emergency exit","Fuel vapors require controlled procedures and no ignition source.","Section 4.3, Fueling"),

  q("Crossings","Railroad crossings","When may a bus proceed after stopping at railroad tracks?","Only after looking and listening and determining all tracks are clear","As soon as another vehicle moves","Whenever the door is closed","Immediately after sounding the horn","The driver must personally verify that crossing is safe.","Section 4.3, Railroad Crossings"),
  q("Crossings","Railroad crossings","What should a bus driver do if traffic will not allow the entire bus to clear the tracks?","Wait before entering the crossing","Stop on the tracks","Follow the vehicle ahead closely","Use the shoulder around the gate","Never enter unless enough space exists beyond the tracks.","Section 4.3, Railroad Crossings"),
  q("Crossings","Railroad crossings","What is a safe gear choice for crossing tracks?","A gear that carries the bus completely across without shifting","Neutral","The highest gear available","A gear selected after entering","Avoiding shifts prevents stalling on the crossing.","Section 4.3, Railroad Crossings"),
  q("Crossings","Drawbridges","After stopping for an uncontrolled drawbridge, when may the bus proceed?","When the draw is fully closed and safe","While the draw is moving","When passengers vote to go","Without checking if traffic is light","The driver must verify the bridge is closed before crossing.","Section 4.3, Drawbridges"),

  q("Emergencies","Evacuation","Which factor should determine the best bus evacuation exit?","The location of fire, traffic, and other hazards","The exit nearest the driver every time","Passenger preference only","The largest piece of baggage","The safest exit route depends on where the danger is located.","Section 4.4, Evacuation"),
  q("Emergencies","Evacuation","After evacuation, where should passengers gather?","At a safe location together and away from traffic","Beside the fuel tank","Directly behind the bus","In the roadway","A controlled assembly area lets the driver account for and protect passengers.","Section 4.4, Evacuation"),

  q("Qualification and rules","Qualification","Besides the Passenger knowledge test, what is normally required to add a P endorsement?","A qualifying skills test in a representative passenger vehicle","Only a vision test","A Tank test","No vehicle test","Passenger endorsement applicants must demonstrate skills in the appropriate vehicle.","Section 4, Passenger Endorsement"),
];

const school = [
  q("Loading and danger zones","Danger zone","Where is the most dangerous area around a school bus?","Close to the bus where the driver may not see a child","Only 100 feet behind","Inside the driver's compartment","At the center aisle","Children nearest the bus can disappear from direct and mirror view.","Section 10.1, Danger Zones"),
  q("Loading and danger zones","Loading","When should the entrance door be opened at a student stop?","After the bus is fully stopped and secured","While approaching the stop","Before warning lights activate","Only after students touch the bus","A secured stop prevents children from approaching a moving bus.","Section 10.2, Loading"),
  q("Loading and danger zones","Loading","What should students do before walking toward the bus?","Wait for the driver's signal and for the bus to stop","Run alongside the bus","Stand in the roadway","Approach from directly behind","Controlled approach keeps students visible and separated from traffic.","Section 10.2, Loading"),
  q("Loading and danger zones","Student crossing","What should the driver check before signaling students across?","All traffic is stopped and the path is clear","Only the left mirror","Only the bus door","Whether the route is late","The driver's signal must follow a complete traffic and danger-zone check.","Section 10.2, Student Crossing"),
  q("Loading and danger zones","Student crossing","If a motorist ignores the bus stop signal, what should the driver do?","Keep students from crossing and report the danger as required","Wave students across quickly","Move the bus into the motorist's lane","Leave the stop immediately","Student movement must wait until the roadway is truly safe.","Section 10.2, Student Crossing"),
  q("Loading and danger zones","Unloading","Where should students move after leaving the bus?","Directly to a safe location away from the danger zone","Alongside the rear wheels","Under the front bumper","Back toward the service door","Promptly clearing the bus area keeps children visible and safe.","Section 10.2, Unloading"),
  q("Loading and danger zones","Unloading","What should the driver do if a student cannot be accounted for after unloading?","Keep the bus stopped and locate the student","Move forward slowly","Back up to search","Assume the child entered a building","The bus must not move until every student is confirmed clear.","Section 10.2, Unloading"),
  q("Loading and danger zones","Backing","If backing cannot be avoided, what support should be used when available?","A responsible spotter","A student standing behind the bus","Only the horn","Another bus following closely","A trained spotter helps monitor areas the driver cannot see.","Section 10.2, Backing"),
  q("Loading and danger zones","Special stops","Why are route stops planned to minimize student crossings?","Crossing traffic creates one of the greatest loading hazards","It reduces fuel tax","It changes bus capacity","It keeps mirrors clean","Fewer road crossings reduce exposure to passing motorists.","Section 10.2, Route Planning"),

  q("Mirrors","Mirror use","Which mirror system helps view the rear tires touching the ground?","The outside flat and convex mirrors","Only crossover mirrors","The interior student mirror","The sun visor","Side mirror coverage helps monitor rear wheel danger areas and traffic.","Section 10.1, Mirror Adjustment"),
  q("Mirrors","Mirror use","What must the driver see in the student mirror?","The entire passenger area including the rear seats","Only the service door","Only traffic behind the bus","The front bumper","Interior mirror coverage supports student supervision and post-trip checks.","Section 10.1, Inside Mirror"),

  q("Crossings","Railroad crossings","What should the school-bus driver do with noise sources before listening for a train?","Silence them and open the service door or window as required","Turn the radio louder","Ask students to move seats","Sound the horn continuously","A quiet bus and an open listening point help detect an approaching train.","Section 10.3, Railroad Crossings"),
  q("Crossings","Railroad crossings","Why must the driver check beyond the first set of tracks?","A second train may be hidden by the first","The bus must change gears there","Warning lights cover only one rail","The rear door must open","Multiple tracks can carry trains from different directions.","Section 10.3, Multiple Tracks"),
  q("Crossings","Railroad crossings","What should a driver do if a crossing signal activates while the bus is already crossing?","Continue forward and clear the tracks without stopping","Stop on the rails","Back toward the gate","Unload students on the tracks","Once committed, clearing the crossing is safer than stopping in the train path.","Section 10.3, Railroad Crossings"),

  q("Emergencies","Evacuation","Who should be assigned to help younger or mobility-limited students during a planned evacuation drill?","Responsible helpers instructed by the driver","Passing motorists","No one","Students chosen after the emergency begins","Preassigned helpers make evacuation faster and more orderly.","Section 10.4, Evacuation Planning"),
  q("Emergencies","Evacuation","What should be taken during an evacuation only if it is immediately available and safe?","Essential emergency equipment","Every student's baggage","The driver's personal items first","Loose seat cushions","People leave first; equipment is secondary and must not delay escape.","Section 10.4, Emergency Evacuation"),

  q("Operations and students","Student management","Where should disruptive students be seated when practical?","Where the driver can monitor them without losing road attention","Beside an emergency exit they can block","On the floor","In the driver's seat","Seat placement may improve supervision while the driver remains focused on driving.","Section 10.5, Student Management"),
  q("Operations and students","Post-trip","Why should the driver check beneath seats during a post-trip inspection?","A sleeping child or dangerous item may be hidden","To measure axle weight","To release spring brakes","To test mirrors","A deliberate walk-through must cover areas not visible from the aisle.","Pupil Transportation Guide, Post-trip Inspection"),
  q("Operations and students","Nebraska operations","When must Nebraska pupil-transportation headlights be used?","At all times while operating","Only after sunset","Only during loading","Only outside city limits","The supplemental Nebraska guide requires headlights during operation.","Pupil Transportation Guide, Operating Regulations"),
  q("Operations and students","Nebraska operations","Outside a city or town, how closely may one Nebraska pupil-transportation vehicle follow another?","Not within 475 feet except when passing","Within 50 feet","Within one vehicle length","There is no special distance","The guide specifies a 475-foot convoy separation outside corporate limits.","Pupil Transportation Guide, Operating Regulations"),
];

export const extraRows = { general, air, combination, passenger, school };

