// Original, manual-grounded technical scenarios. Correct answer is always first;
// the app shuffles answer order for every session.
const q=(domain,topic,prompt,correct,wrong1,wrong2,wrong3,explanation,source,reviewRefs=[])=>[domain,topic,prompt,correct,wrong1,wrong2,wrong3,explanation,source,reviewRefs];

const general=[
q("Licensing and rules","Vehicle classification","A tractor is rated at 19,500 pounds and its trailer at 12,000 pounds. Which CDL class normally applies?","Class A, because the combination is at least 26,001 pounds and the trailer exceeds 10,000 pounds","Class B, because the tractor alone is under 26,001 pounds","Class C, because only actual scale weight matters","No CDL, because neither unit alone is 26,001 pounds","Classification uses rated combination weight and the towed unit's rating, not only the tractor rating or current load.","Nebraska Specifics, Classes of Commercial Motor Vehicles",["REV-GEN-LIC-01"]),
q("Licensing and rules","Vehicle classification","A single truck is rated at 28,000 pounds and tows a 7,000-pound trailer. Which class normally covers it?","Class B","Class A","Class C","No CDL","A heavy single vehicle rated at least 26,001 pounds remains Class B when the towed unit is 10,000 pounds or less.","Nebraska Specifics, Classes of Commercial Motor Vehicles",["REV-GEN-LIC-01"]),
q("Licensing and rules","Restrictions","A driver skills-tests in a truck with air-over-hydraulic brakes. Which restriction should be expected?","Z - no full-air-brake-equipped CMV","L - no air-brake-equipped CMV of any kind","E - no manual transmission","O - no tractor-trailer","The Z restriction applies when the test vehicle has air-over-hydraulic rather than full air brakes.","Nebraska Specifics, CDL Restrictions",["REV-GEN-LIC-02"]),
q("Licensing and rules","Learner permit","A CLP holder wants to practice in a passenger bus. Who must sit in the front seat?","A CDL holder qualified for that passenger vehicle","Any licensed adult over age 21","A mechanic familiar with the bus","Another CLP holder with more experience","The supervising CDL holder must be properly licensed for the class and type being practiced and occupy the required seat.","Nebraska Specifics, Commercial Learner's Permit",["REV-GEN-LIC-03"]),
q("Licensing and rules","Skills testing","A Nebraska applicant passes inspection and basic control, but the CLP expires before the road test. What is required?","Renew eligibility and repeat all three skills-test segments","Take only the road test within 30 days","Retake only basic control and road","Convert the passed segments to a full CDL","Passed segments do not remain valid when the CLP expires before the full sequence is completed.","Nebraska Specifics, CDL Skills Testing",["REV-GEN-LIC-04"]),
q("Licensing and rules","Medical certification","Why is an accurate CDL self-certification category operationally important?","It determines whether the driver must maintain a medical examiner's certificate","It determines the truck's registered axle weight","It replaces the need for endorsements","It selects the vehicle inspection interval","The declared operating category controls which medical-document requirements apply.","Nebraska Specifics, Medical Certification",["REV-GEN-LIC-05"]),
q("Licensing and rules","Disqualification","A CMV driver refuses a required alcohol test. What is the CDL consequence?","The refusal can trigger disqualification","Only the vehicle registration is suspended","There is no CDL effect without a crash","The driver receives an automatic passenger endorsement restriction","Refusal of a required test is treated as a serious CDL alcohol-rule violation.","Section 1.3, Driver Disqualifications",["REV-GEN-LIC-06"]),
q("Licensing and rules","Endorsements","A driver will carry students in a school bus designed for 16 people including the driver. Which endorsements are normally needed?","Both P and S","Only N","Only T","No endorsement if the route stays in Nebraska","School-bus operation requires passenger and school-bus qualifications in addition to the proper CDL class.","Nebraska Specifics, CDL Endorsements",["REV-GEN-LIC-07"]),
q("Licensing and rules","Documents","Why should two Nebraska principal-address documents come from different issuing sources?","They provide independent verification of the applicant's address","They prove ownership of two vehicles","They replace identity documents","They remove the need for a Social Security number","Nebraska uses two different-source documents to establish principal residence.","Nebraska Specifics, Principal Address Verification",["REV-GEN-LIC-08"]),
q("Licensing and rules","Entry-level training","When must required entry-level driver training be recorded for a first-time Class B applicant?","Before the applicant takes the required CDL skills test","After the first CDL renewal","Only after failing the road test","Before taking any ordinary car-license test","Required ELDT completion must be verified before applicable CDL skills testing.","Nebraska Specifics, Entry Level Driver Training",["REV-GEN-LIC-09"]),
q("Licensing and rules","License classes","A 24,000-pound-rated vehicle carries placarded hazardous material. Which CDL class can apply based on that use?","Class C","Class A only","Class B only","No CDL because the rating is below 26,001 pounds","Class C can cover a smaller CMV used for placarded hazardous materials.","Nebraska Specifics, Classes of Commercial Motor Vehicles",["REV-GEN-LIC-01"]),
q("Licensing and rules","Driver responsibility","After a qualifying traffic conviction, why must a commercial driver notify the employer promptly?","CDL rules impose reporting duties so the employer knows the driver's status","The employer must automatically pay the fine","The notice replaces the court record","The notice increases the vehicle weight rating","Commercial drivers have specific conviction-reporting responsibilities beyond ordinary vehicle paperwork.","Section 1.2, Driver Responsibilities",["REV-GEN-LIC-10"]),

q("Inspection and cargo","Steering inspection","Which finding makes a steering-system inspection especially urgent?","A loose steering-gear mount or missing fastener","A clean steering wheel","A full windshield-washer reservoir","A warm engine after operation","Loose, cracked, or missing steering components can cause loss of directional control.","Section 2.1, Steering System",["REV-GEN-INS-01"]),
q("Inspection and cargo","Suspension inspection","A leaf spring is shifted so it may contact a tire. What should the driver do?","Have the defect corrected before operating","Drive slowly until the next annual inspection","Reduce cargo but leave the spring in place","Add air to the tire to create clearance","A displaced spring that can strike a tire is an unsafe suspension defect.","Section 2.1, Suspension System",["REV-GEN-INS-02"]),
q("Inspection and cargo","Tire inspection","What minimum tread depth is required in every major groove of a front steering-axle tire?","4/32 inch","2/32 inch","1/32 inch","6/32 inch","Front tires require at least 4/32 inch in every major groove; other tires generally require 2/32 inch.","Section 2.1, Tires",["REV-GEN-INS-03"]),
q("Inspection and cargo","Emergency equipment","Which set matches the basic emergency equipment checked during inspection?","Fire extinguisher, spare electrical fuses unless circuit breakers are used, and three warning triangles","Tow chain, shovel, and one flare","First-aid kit, two cones, and jumper cables only","Two fire extinguishers and one triangle only","The manual inspection list includes a properly charged extinguisher, spare fuses when applicable, and three red reflective triangles.","Section 2.1, Emergency Equipment",["REV-GEN-INS-04"]),
q("Inspection and cargo","Hydraulic brakes","With the engine off, how is a hydraulic brake leak check performed?","Pump the pedal, hold firm pressure, and verify the pedal does not move toward the floor","Start the engine and release every brake","Press the accelerator while watching tire pressure","Apply the parking brake and ignore pedal movement","A pedal that continues toward the floor under steady pressure can indicate a hydraulic leak.","Section 2.1, Hydraulic Brake Check",["REV-GEN-INS-05"]),
q("Inspection and cargo","Cargo securement","How many tiedowns are required at minimum for a 20-foot article when no special rule requires more?","Two","One","Three for every load regardless of length","None if the cargo is heavy","The general rule requires at least one tiedown for each 10 feet of cargo, with at least two tiedowns for any cargo article.","Section 3.3, Cargo Securement",["REV-GEN-CAR-01"]),
q("Inspection and cargo","Sealed loads","What remains the driver's responsibility when a load is sealed and cannot be inspected internally?","Verify legal gross and axle weights and secure the container or doors","Break every seal before departure","Assume the shipper carries all responsibility","Skip all cargo checks during the trip","A seal limits inspection of the contents but does not remove weight and external securement duties.","Section 3.3, Sealed and Containerized Loads",["REV-GEN-CAR-02"]),
q("Inspection and cargo","Weight distribution","A loaded truck has very light steering and poor directional control. Which loading error is a likely cause?","Too little weight on the front axle","Too much washer fluid","A low-mounted load","Too many warning triangles","Insufficient steering-axle weight reduces front-tire traction and steering control.","Section 3.2, Weight and Balance",["REV-GEN-CAR-03"]),

q("Driving and control","Backing","Why is driver-side backing preferred when a choice exists?","The driver can see the trailer path better in the left mirror","It eliminates every blind spot","It prevents all trailer offtracking","It allows backing at normal road speed","Backing toward the visible side gives better observation and earlier correction.","Section 2.2, Backing Safely",["REV-GEN-CTL-01"]),
q("Driving and control","Backing","What hand signal must a driver and spotter agree on before backing?","Stop","Turn the radio louder","Speed up","Release the parking brake","The driver must stop immediately when the spotter gives the agreed stop signal or disappears from view.","Section 2.2, Backing Safely",["REV-GEN-CTL-02"]),
q("Driving and control","Shifting","Which two situations call for selecting a lower gear before the maneuver?","Before starting down a hill and before entering a curve","After clearing a hill and after leaving a curve","Only while crossing railroad tracks","Whenever cruise control is engaged","Downshifting in advance preserves control and avoids shifting at a critical point.","Section 2.3, Shifting Gears",["REV-GEN-CTL-03"]),
q("Driving and control","Seeing","At 55 mph, what distance does a 12-to-15-second look-ahead represent?","About one-quarter mile","About one truck length","About 100 feet","Exactly one mile","At highway speed the recommended visual lead is roughly a quarter mile, providing time for smooth decisions.","Section 2.4, Seeing Ahead",["REV-GEN-SEE-01"]),
q("Driving and control","Following distance","A 30-foot CMV travels at 55 mph in good conditions. What minimum following interval fits the manual's rule?","Four seconds","Two seconds","Three seconds","Six seconds only when empty","Allow one second per 10 feet below 40 mph and add one second above 40 mph: three plus one equals four.","Section 2.7, Following Distance",["REV-GEN-SPC-01"]),
q("Driving and control","Turns","Why should a driver avoid swinging left before a right turn?","A vehicle may try to pass on the right and become trapped","It prevents the trailer from tracking","It makes the turn signal brighter","It automatically raises the trailer","A wide left swing can invite another road user into the space needed by the trailer.","Section 2.7, Turns",["REV-GEN-SPC-02"]),
q("Driving and control","Curves","When should most speed reduction for a curve occur?","Before entering the curve","At the sharpest point in the curve","After leaving the curve","Only if the trailer begins to skid","Entering at a controlled speed avoids hard braking and traction loss while steering.","Section 2.6, Curves",["REV-GEN-CTL-05"]),
q("Driving and control","Railroad crossings","Why can a low-slung trailer become trapped at a raised crossing?","The landing gear or trailer frame can hang on the track profile","The air compressor stops at every rail","The fifth wheel unlocks automatically","The tires lose all pressure near tracks","Humped crossings can high-center equipment with limited underbody clearance.","Section 2.15, Railroad-highway Crossings",["REV-GEN-RRX-01"]),
q("Driving and control","Railroad crossings","About how long can a typical tractor-trailer need to clear a double-track crossing?","More than 15 seconds","Less than two seconds","Exactly five seconds","One minute in every case","Long combination vehicles need substantial time; the manual warns a typical unit can require more than 15 seconds.","Section 2.15, Railroad-highway Crossings",["REV-GEN-RRX-02"]),
q("Driving and control","Mountain driving","What is the correct snub-braking sequence on a long downgrade?","Brake firmly enough to reduce about 5 mph below safe speed, release, and repeat when safe speed returns","Ride the brakes lightly without releasing","Shift to neutral and pump rapidly","Use only the parking brake","Proper snub braking supplements engine braking while allowing brakes to cool between applications.","Section 2.16, Proper Braking Technique",["REV-GEN-MTN-01"]),
q("Driving and control","Emergency steering","Why must countersteering immediately follow an avoidance steer?","It keeps the vehicle from continuing into another lane or off the road","It increases engine braking","It applies trailer spring brakes","It locks the steering axle straight","The return steering movement is part of the same evasive maneuver and restores the intended path.","Section 2.17, Steering to Avoid a Crash",["REV-GEN-EMR-01"]),
q("Driving and control","Tire failure","After a front-tire blowout, why should the driver avoid hard braking at first?","Hard braking can worsen the pull and reduce control","It will overcharge the air tanks","It makes the horn inoperative","It raises the vehicle's center of gravity","Firm steering and gradual slowing help stabilize the vehicle before braking to a stop.","Section 2.17, Tire Failure",["REV-GEN-EMR-02"]),
q("Driving and control","ABS","How should a driver make an emergency stop in an ABS-equipped vehicle?","Brake firmly, maintain pressure, and steer as needed without pumping","Pump the pedal rapidly throughout the stop","Use only the parking brake","Release the pedal whenever ABS activates","ABS is designed for firm continuous braking while helping preserve steering control.","Section 2.18, Antilock Braking Systems",["REV-GEN-ABS-01"]),
q("Driving and control","Skid recovery","What is the first control change for a front-wheel skid caused by excessive speed?","Stop steering and braking so hard and let the vehicle slow","Accelerate sharply","Apply the trailer hand valve","Turn farther into the curve","Reducing the demand on the front tires allows traction and steering response to return.","Section 2.19, Front-wheel Skids",["REV-GEN-SKD-01"]),
q("Driving and control","Roadside warning","On a two-way undivided road after an emergency stop, where is the farthest rear warning triangle generally placed?","About 100 feet behind the vehicle","At the rear bumper only","About 10 feet behind","About 500 feet behind in every situation","The standard placement provides advance warning in both directions, adjusted for hills, curves, or obstructions.","Section 2.5, Warning Others",["REV-GEN-INS-04"]),
q("Driving and control","Vehicle control","When starting on an uphill grade, how can rollback be prevented?","Keep the parking brake applied until engine power begins pulling the vehicle","Release every brake before applying power","Shift to neutral and coast backward","Use the trailer hand valve as the only holding brake","Coordinating power with parking-brake release prevents uncontrolled rollback.","Section 2.2, Starting on a Grade",["REV-GEN-CTL-06"]),
q("Driving and control","Retarders","Why should a retarder be turned off on a slippery road?","It can cause drive wheels to lose traction","It disables the steering gear","It empties the air tanks instantly","It raises tire pressure","Retarder force acts at the drive wheels and can contribute to a skid when traction is poor.","Section 2.3, Retarders",["REV-GEN-CTL-07"]),

q("Hazards and conditions","Hazard planning","Why should a driver form an emergency plan as soon as a hazard is recognized?","Early planning reduces reaction time if the hazard becomes immediate","It permits the driver to increase speed","It removes the need to scan mirrors","It guarantees other drivers will yield","Deciding where to brake or steer before the conflict develops improves response time.","Section 2.8, Seeing Hazards",["REV-GEN-HAZ-01"]),
q("Hazards and conditions","Distracted driving","What is the safest way to enter route information into a navigation device?","While parked in a safe location before moving","While descending a straight grade","At a red light in a travel lane","While following another truck closely","Programming before departure keeps visual, manual, and mental attention on driving.","Section 2.9, Distracted Driving",["REV-GEN-DST-01"]),
q("Hazards and conditions","Aggressive driving","Which behavior distinguishes road rage from aggressive driving?","Road rage involves a criminal assault using a vehicle or weapon","Road rage means driving five mph under the limit","Aggressive driving is always a felony","There is no difference","Aggressive driving is dangerous traffic behavior; road rage escalates to criminal assault.","Section 2.10, Aggressive Drivers and Road Rage",["REV-GEN-AGR-01"]),
q("Hazards and conditions","Night driving","What does it mean to overdrive the headlights?","Stopping distance is longer than the roadway visible in the beams","The high beams are too bright for the battery","The vehicle is traveling below the limit","The headlights are aimed at the shoulder","Speed must be low enough to stop within the illuminated distance.","Section 2.11, Driving at Night",["REV-GEN-NGT-01"]),
q("Hazards and conditions","Wet brakes","After driving through deep water, how should brake function be restored?","Apply light pressure while driving slowly until the brakes heat and dry","Set the parking brake fully at highway speed","Cool the brakes with more water","Ignore them until the next stop","Gentle controlled application can dry wet linings; the driver must verify braking before resuming normal speed.","Section 2.12, Wet Brakes",["REV-GEN-WTH-01"]),
q("Hazards and conditions","Hot weather","Why must air never be released from a hot tire to return it to a cold-pressure reading?","The pressure will become too low after the tire cools","Hot tires have no internal pressure","Releasing air strengthens the sidewall","It improves traction on ice","Heat normally raises pressure; bleeding a hot tire can leave it dangerously underinflated later.","Section 2.13, Tires",["REV-GEN-WTH-02"]),
q("Hazards and conditions","Fog","Which headlight setting gives the best practical visibility in fog?","Low beams","High beams","Parking lights only","No lights","High beams reflect from fog and create glare, while low beams reduce reflection.","Section 2.11, Driving in Fog",["REV-GEN-NGT-02"]),

q("Emergencies and fitness","Crash scene","What is the first operational priority after stopping at a crash scene?","Protect the area so another collision does not occur","Move every injured person immediately","Collect cargo before placing warnings","Turn off all warning flashers","Vehicle position, flashers, and warning devices should first protect people from approaching traffic.","Section 2.20, Accident Procedures",["REV-GEN-ACC-01"]),
q("Emergencies and fitness","Vehicle fires","Which maintenance problem commonly starts a tire fire?","Underinflation or dual tires rubbing together","A clean wheel bearing","Proper cargo balance","A fully charged extinguisher","Low pressure and rubbing create excessive heat that can ignite tires.","Section 2.21, Fires",["REV-GEN-FIR-01"]),
q("Emergencies and fitness","Fire extinguishers","Why is a B:C extinguisher unsuitable for a burning seat or mattress?","B:C ratings cover flammable liquids and electrical equipment, not ordinary combustible material","It contains too much water","It can be used only outdoors","It works only on metal fires","Class A capability is needed for common combustibles such as wood, paper, cloth, or upholstery.","Section 2.21, Fires",["REV-GEN-FIR-02"]),
q("Emergencies and fitness","Alcohol","What actually lowers a person's blood alcohol concentration after drinking?","Time as the body processes the alcohol","Black coffee","A cold shower","Fresh air","Coffee, exercise, and showers do not speed the liver's fixed alcohol-processing rate.","Section 2.22, Alcohol and Driving",["REV-GEN-ALC-01"]),
q("Emergencies and fitness","Medication","What should a driver do before using a new cold medicine on duty?","Confirm with a doctor or pharmacist that it will not impair safe driving","Double the dose to shorten symptoms","Use it only with an energy drink","Assume nonprescription medicine cannot impair driving","Common medicines can cause drowsiness or slower reactions and must be evaluated before driving.","Section 2.23, Staying Alert and Fit to Drive",["REV-GEN-FIT-01"]),
q("Emergencies and fitness","Brake failure","If service brakes fail on a downgrade, what roadway feature should the driver use when available?","An escape ramp","A runaway lane only after stopping","The opposing shoulder","A railroad crossing","Escape ramps are designed to absorb a heavy vehicle's energy when normal braking cannot control speed.","Section 2.17, Brake Failure",["REV-GEN-EMR-03"]),
];

const air=[
q("Components","Air tanks","Why must reservoirs be drained even when the vehicle has automatic drains?","To verify removal of moisture and oil that can damage or freeze the system","To release the spring brakes","To increase brake-lining thickness","To test the horn circuit","Water and compressor oil can collect in tanks; automatic drains should still be checked.","Section 5.1, Air Storage Tanks",["REV-AIR-CMP-01"]),
q("Components","Supply gauge","What does the supply-pressure gauge tell the driver?","How much air pressure is available in the reservoirs","How much force each brake shoe applies","The trailer's cargo weight","The steering-axle tire pressure","The supply gauge monitors stored system pressure, often for both primary and secondary circuits.","Section 5.1, Supply Pressure Gauges",["REV-AIR-CMP-02"]),
q("Components","Governor","During a governor check, what should happen near the manufacturer's cut-out pressure?","The compressor stops building pressure","The spring brakes apply","The low-air warning activates","The service brakes release all air","Cut-out is the upper governed pressure at which the compressor unloads.","Section 5.1, Air Compressor Governor",["REV-AIR-CMP-03"]),
q("Components","Safety valve","At approximately what pressure is the air-tank safety valve designed to open?","150 psi","60 psi","30 psi","200 psi","The safety valve protects tanks and the system from excessive pressure, typically opening around 150 psi.","Section 5.1, Safety Valve",["REV-AIR-CMP-04"]),
q("Components","Foundation brakes","In an S-cam brake, what action forces the shoes against the drum?","The rotating S-cam spreads the brake shoes","The governor pushes the tire inward","The air tank expands the drum","The ABS lamp moves the slack adjuster","Air moves the pushrod and slack adjuster, rotating the S-cam to spread the shoes.","Section 5.1, Foundation Brakes",["REV-AIR-CMP-05"]),
q("Components","Slack adjusters","With brakes released and wheels chocked, what manual slack-adjuster movement signals a possible adjustment problem?","More than about one inch where the pushrod attaches","Any movement less than one-quarter inch","A firm pushrod with no visible damage","A warm brake drum after normal use","Excessive pushrod travel can indicate an out-of-adjustment brake that needs qualified service.","Section 5.3, Slack Adjusters",["REV-AIR-TST-01"]),
q("Components","Spring brakes","How do spring brakes apply when system pressure is lost?","Powerful mechanical springs apply them as air pressure is released","The compressor reverses direction","The driver must pump hydraulic fluid","ABS wheel sensors tighten the shoes","Air holds the springs back; loss of pressure allows the springs to apply the brakes.","Section 5.1, Spring Brakes",["REV-AIR-CMP-06"]),
q("Components","Dual systems","What makes a dual air-brake system safer than a single circuit?","Two separate systems can preserve partial braking after one side loses pressure","It eliminates all air leaks","It uses one tank with two gauges only","It makes brake inspections unnecessary","Primary and secondary circuits have separate reservoirs and lines controlled by the same pedal.","Section 5.2, Dual Air Brake Systems",["REV-AIR-DUA-01"]),
q("Components","ABS identification","Where can a driver look for evidence that a vehicle has ABS?","An ABS malfunction lamp and required component labels or indicators","A blue parking-brake knob","A hydraulic-fluid sight glass only","A second steering wheel","ABS-equipped vehicles have warning lamps, and many trailers have an exterior indicator.","Section 5.1, Antilock Braking Systems",["REV-AIR-CMP-07"]),
q("Components","Front brakes","Why should front-wheel air brakes remain active under normal conditions?","They supply important stopping power and are designed for stable braking","They are used only for parking","They increase brake lag","They prevent the air compressor from cycling","Modern front brakes contribute essential braking and should not be disabled except as specifically allowed.","Section 5.1, Front Brake Limiting Valves",["REV-AIR-CMP-08"]),

q("Inspection and tests","Pressure buildup","For a dual system, what buildup performance should be checked with the engine at operating rpm?","Pressure should rise from 85 to 100 psi within 45 seconds unless the manufacturer specifies otherwise","Pressure should fall from 100 to 85 psi in 45 seconds","Pressure must reach 150 psi in 10 seconds","Only one gauge needs to rise above 55 psi","Adequate compressor output is verified by the specified 85-to-100 psi buildup interval.","Section 5.3, Air Pressure Buildup Rate",["REV-AIR-TST-02"]),
q("Inspection and tests","Static leak test","What is the maximum static pressure loss for a combination vehicle with brakes released?","3 psi in one minute","1 psi in one minute","4 psi in one minute","6 psi in two minutes","After initial pressure stabilizes, a combination vehicle should not lose more than 3 psi per minute with brakes released.","Section 5.3, Air Leakage Rate",["REV-AIR-TST-03"]),
q("Inspection and tests","Applied leak test","What is the maximum applied pressure loss for a combination vehicle?","4 psi in one minute","2 psi in one minute","3 psi in five minutes","10 psi in one minute","With the service brake fully applied after stabilization, combination loss should not exceed 4 psi per minute.","Section 5.3, Air Leakage Rate",["REV-AIR-TST-03"]),
q("Inspection and tests","Low-air warning","How is the low-air warning tested?","Turn electrical power on and fan the brakes until the warning activates before pressure falls below the required level","Run the engine at high idle until the warning sounds","Set only the trailer hand valve","Drain one tank with the engine running at highway speed","Fanning the service brake reduces stored pressure so the warning threshold can be observed.","Section 5.3, Low Air Pressure Warning",["REV-AIR-TST-04"]),
q("Inspection and tests","Spring-brake test","How is automatic spring-brake application checked?","Continue fanning pressure down until the parking controls pop out in the manufacturer's range","Hold the accelerator down until the knobs pop out","Pull the ABS fuse","Open the radiator cap","The test verifies that loss of air automatically triggers the emergency/parking brake controls.","Section 5.3, Spring Brake Check",["REV-AIR-TST-05"]),

q("Operation and braking","Brake lag","At 55 mph, about how much distance can air-brake lag add before braking begins?","About 32 feet","About 3 feet","About 100 feet","No distance at all","Air must travel through the system, adding roughly four-tenths of a second or about 32 feet at 55 mph.","Section 5.4, Stopping Distance",["REV-AIR-OPS-01"]),
q("Operation and braking","Normal braking","What pedal technique produces a smooth normal stop with air brakes?","Apply controlled pressure, then release as needed to avoid a harsh stop","Pump the pedal continuously","Use only the parking brake","Hold the trailer hand valve down","Controlled service-brake pressure manages deceleration without overheating or wheel lock.","Section 5.4, Normal Stops",["REV-AIR-OPS-02"]),
q("Operation and braking","Downgrades","What is the service brake's role on a long, steep downgrade?","Supplement the engine's braking effect","Provide all speed control while the transmission is in neutral","Replace choosing a low gear","Keep the compressor unloaded","The correct gear and engine braking carry most of the load; properly timed service applications control speed.","Section 5.4, Braking on Downgrades",["REV-AIR-OPS-03"]),
q("Operation and braking","Brake fade","What operating error most directly causes brake fade on a downgrade?","Continuous excessive brake use that overheats linings and drums","Starting in a low gear","Draining air tanks daily","Checking mirrors too often","Heat reduces friction and can expand drums away from the linings, weakening braking.","Section 5.4, Brake Fading or Failure",["REV-AIR-OPS-04"]),
q("Operation and braking","ABS braking","How should a tractor-trailer with working ABS be braked in an emergency?","Apply firm pressure and do not pump the pedal","Use the trailer hand valve only","Release the pedal when pulsation begins","Repeatedly set and release the parking brake","ABS modulates wheel pressure automatically while the driver maintains firm braking.","Section 5.4, Emergency Stops",["REV-AIR-OPS-05"]),

q("Low pressure and safety","Low-air response","What should a driver do if the low-air warning comes on while moving?","Stop safely before spring brakes apply automatically and have the system repaired","Drive faster to build pressure","Pull the parking knob immediately in traffic","Continue until the next fuel stop","Low pressure means available braking is being lost and automatic spring-brake application may follow.","Section 5.1, Low Air Pressure Warning",["REV-AIR-SAF-01"]),
q("Low pressure and safety","Parking brakes","When may a driver leave an air-brake vehicle without setting the parking brakes?","Only in a rare situation where very hot brakes or freezing conditions make spring-brake use unsafe, with wheels securely chocked","Whenever the stop will be under five minutes","Whenever the engine remains running","Whenever the road appears level","Parking brakes are normally mandatory; narrowly defined brake-temperature conditions require secure wheel chocks instead.","Section 5.4, Parking Brakes",["REV-AIR-SAF-02"]),
q("Low pressure and safety","Spring brakes","Why should the brake pedal not be pushed when spring brakes are on?","Combined spring and service force can damage brake components","It drains engine oil","It turns off ABS permanently","It opens the safety valve at 60 psi","Applying both forces together can overload brake hardware.","Section 5.1, Spring Brakes",["REV-AIR-SAF-03"]),
q("Low pressure and safety","Dual-system warning","In a dual system, what does one circuit at very low pressure mean?","Either the front or rear service brakes may not operate fully, increasing stopping distance","All brakes automatically become hydraulic","The remaining circuit doubles its capacity","Only the horn is affected","A dual system may retain partial braking, but reduced capability requires an immediate safe stop.","Section 5.2, Dual Air Brake Systems",["REV-AIR-DUA-01"]),
q("Low pressure and safety","Tank draining","How often should manually drained air tanks be drained in normal service?","At the end of each working day","Once per year","Only when the low-air warning sounds","Every 10,000 miles","Daily draining removes accumulated water and oil before they freeze or damage components.","Section 5.4, Parking Brakes; Section 5.1, Air Tanks",["REV-AIR-OPS-06"]),
];

const combination=[
q("Vehicle dynamics","Rollover","Which two driver actions are most important for preventing a combination-vehicle rollover?","Keep cargo low and centered, and enter curves slowly","Brake hard in curves and load high","Use the hand valve in every turn","Shift on railroad tracks","A low center of gravity and controlled curve speed reduce lateral force and rollover risk.","Section 6.1, Rollover Risks",["REV-COM-DYN-01"]),
q("Vehicle dynamics","Crack-the-whip","In a doubles combination, which unit is most likely to roll during a sudden steering move?","The last trailer","The tractor","The first trailer only","Every unit has identical rollover force","Rearward amplification makes the last trailer respond most sharply to rapid steering.","Section 6.1, Preventing Rollover",["REV-COM-DYN-02"]),
q("Vehicle dynamics","Offtracking","What is offtracking in a combination vehicle?","The rear wheels follow a path inside the path of the steering wheels","The trailer moves outside every curve","The tractor loses air pressure","The fifth wheel slides rearward automatically","Long vehicles cut inside on turns, so the driver must protect curb and traffic clearance.","Section 6.1, Steering with a Trailer",["REV-COM-DYN-03"]),
q("Vehicle dynamics","Trailer skid","Why should the trailer hand valve not be used to straighten a jackknife?","It can lock trailer wheels and make the skid worse","It applies tractor steering brakes","It raises the landing gear","It closes every shutoff valve","Trailer-only braking reduces trailer traction and may accelerate the jackknife.","Section 6.1, Trailer Skids",["REV-COM-DYN-04"]),
q("Vehicle dynamics","Braking","Why do empty combination vehicles sometimes require more stopping distance than expected?","Lightly loaded wheels can lock more easily and suspension may bounce","Empty trailers always have stronger traction","The air compressor runs more slowly when empty","The tractor protection valve stays closed","Low axle loading can reduce available tire grip even though the vehicle weighs less.","Section 6.1, Brake Early",["REV-COM-DYN-05"]),
q("Vehicle dynamics","Railroad crossings","Which trailer design has greater risk of high-centering at a raised railroad crossing?","A low-clearance trailer with landing gear or frame close to the roadway","A short pickup bed","A high-floor straight truck only","Any trailer with ABS","Low-slung equipment can become stuck on the crossing profile.","Section 6.1, Railroad-highway Crossings",["REV-COM-DYN-06"]),
q("Vehicle dynamics","ABS","If only the trailer has ABS, how should an emergency stop be made?","Brake firmly as usual; the trailer ABS helps prevent its wheels from locking","Use only the trailer hand valve","Pump the pedal because tractor ABS is absent","Release all brakes in a curve","ABS on any equipped unit provides protection there while normal controlled braking remains required for the combination.","Section 6.1, Antilock Brake Systems",["REV-COM-DYN-07"]),

q("Backing and inspection","Backing setup","Which setup gives the safest backing path when both sides are available?","A nearly straight driver-side approach","A sharp blind-side curve","A fast S-shaped path","A path that keeps the tractor jackknifed","A straight, visible path minimizes steering corrections and blind-side exposure.","Section 6.1, Backing with a Trailer",["REV-COM-BCK-01"]),
q("Backing and inspection","Backing correction","When the trailer begins drifting off the intended path, what should the driver do?","Correct the drift early with small steering movements","Wait until the trailer reaches a sharp angle","Accelerate to straighten it","Apply the trailer hand valve","Early corrections prevent the error from growing into a jackknife or blind-side conflict.","Section 6.1, Backing with a Trailer",["REV-COM-BCK-02"]),
q("Backing and inspection","Air lines","What defect should be checked where glad hands connect?","Damaged seals or poor locking that can leak or separate","Matching paint color","A warm electrical cord","Trailer-door clearance","Seals and couplers must be clean, secure, and leak-free.","Section 6.5, Combination Vehicle Inspection",["REV-COM-INS-01"]),
q("Backing and inspection","Coupling inspection","What visual condition confirms correct fifth-wheel contact after coupling?","No gap between the upper and lower fifth wheel","A one-inch gap","The trailer apron resting only on the jaws","Landing gear carrying the trailer weight","Full plate contact supports the trailer and indicates the kingpin entered at the proper height.","Section 6.3, Inspecting the Coupling",["REV-COM-CPL-02"]),
q("Backing and inspection","Trailer brakes","How can trailer service brakes be checked at low speed?","Move slowly and apply the trailer hand valve briefly to feel braking","Pull the tractor parking control while moving","Disconnect the service line","Open the rear emergency shutoff valve","The hand valve is appropriate for a low-speed brake test, not routine road braking.","Section 6.5, Trailer Service Brake Check",["REV-COM-TST-05"]),

q("Coupling and uncoupling","Trailer height","What can happen if the trailer is too high before coupling?","The tractor may pass under without the kingpin entering the locking jaws","The landing gear automatically retracts","The kingpin always locks above the fifth wheel","The emergency line fills with hydraulic fluid","The trailer should be low enough for the tractor to lift it slightly and make full fifth-wheel contact.","Section 6.3, Coupling Tractor-semitrailers",["REV-COM-CPL-01"]),
q("Coupling and uncoupling","Lock check","How should the driver verify that fifth-wheel jaws locked around the kingpin?","Look into the back of the fifth wheel and perform a gentle tug test","Rely only on the release handle position","Raise the landing gear before checking","Pull the trailer supply out while moving","Visual and tug checks together verify the mechanical connection.","Section 6.3, Inspecting the Coupling",["REV-COM-CPL-03"]),
q("Coupling and uncoupling","Landing gear","Before road travel, how should landing gear be positioned?","Fully raised with the crank handle secured","Just clear of the pavement","Half raised to support bumps","Lowered until it touches during turns","Fully raised gear preserves ground clearance and prevents damage.","Section 6.3, Coupling Tractor-semitrailers",["REV-COM-CPL-04"]),
q("Coupling and uncoupling","Uncoupling","Why should a trailer without spring brakes be chocked before air lines are disconnected?","It may roll when air pressure is removed","Chocks increase reservoir pressure","They unlock the fifth wheel","They protect the electrical cable from heat","Without spring parking brakes, the trailer needs a mechanical restraint before losing air.","Section 6.2, Trailer Air Tanks",["REV-COM-AIR-05"]),

q("Air and trailer brakes","Service line","What information does pressure in the service line carry to trailer relay valves?","How much braking force the driver is requesting","The trailer's cargo weight","The tractor's fuel level","The fifth-wheel slide position","Service-line pressure is the control signal created by the foot brake or test hand valve.","Section 6.2, Service Air Line",["REV-COM-AIR-03"]),
q("Air and trailer brakes","Emergency line","What are the two main jobs of the trailer emergency line?","Supply reservoir air and trigger emergency braking after a major pressure loss","Control turn signals and ABS lamps","Raise landing gear and unlock jaws","Apply only tractor steering brakes","The supply/emergency line charges trailer tanks and protects the trailer if the line separates or loses pressure.","Section 6.2, Emergency Air Line",["REV-COM-AIR-04"]),
q("Air and trailer brakes","Shutoff valves","How should shutoff valves be positioned in a multiple-trailer air system?","Open on intermediate units and closed at the rear of the last trailer","Closed on every trailer","Open only at the rear of the last trailer","All service valves open and all supply valves closed","Air must flow through each unit while the unused outlets at the end remain closed.","Section 6.2, Shut-off Valves",["REV-COM-AIR-06","REV-COM-TST-01"]),
q("Air and trailer brakes","Tractor protection test","What result is expected while fanning air pressure down during a tractor-protection test?","The trailer supply control pops out in the manufacturer's specified range","The landing gear rises","The fifth-wheel jaws open","The service line becomes hydraulic","Automatic closure protects tractor air if trailer pressure is lost, usually with control movement in the specified low-pressure range.","Section 6.5, Tractor Protection Valve Test",["REV-COM-TST-03"]),
];

const passenger=[
q("Inspection and loading","Interior inspection","Which interior defect requires attention before carrying passengers?","A loose seat frame or blocked emergency exit","A clean aisle","A secured baggage rack","Readable emergency-exit labels","Seats, handholds, aisles, and exits must be secure, clear, and serviceable.","Section 4.1, Vehicle Inspection",["REV-PAS-INS-01"]),
q("Inspection and loading","Emergency equipment","What should a bus driver verify about emergency exits during inspection?","They operate correctly, close securely, and have readable markings","They are locked so passengers cannot use them","Only the front door opens","Exit buzzers are disconnected","Emergency exits must be usable, identified, and secured against unintended opening.","Section 4.1, Emergency Exits",["REV-PAS-INS-01"]),
q("Inspection and loading","Hazardous materials","Which material is prohibited on a passenger bus?","A labeled cylinder of poison gas","A small properly packaged medical oxygen cylinder","Ordinary passenger baggage","A modest amount of allowed small-arms ammunition when lawful","Passenger vehicles may carry only limited permitted hazardous materials and must never carry certain highly dangerous classes such as poison gas.","Section 4.2, Hazardous Materials",["REV-PAS-HZM-01"]),
q("Inspection and loading","Hazardous materials","What should the driver do with an unlabeled package that appears to contain hazardous material?","Refuse it until its contents and legality are established","Place it beside the driver","Store it in the aisle","Accept it if the passenger promises it is safe","The driver must know what is being transported and reject unknown or prohibited material.","Section 4.2, Hazardous Materials",["REV-PAS-HZM-02"]),
q("Inspection and loading","Standee line","What does the standee line mark?","The forward boundary behind which standing passengers must remain","The location where baggage may block the aisle","The rear-door emergency-release zone","The bus's legal parking position","Passengers standing forward of the line can obstruct the driver's view and controls.","Section 4.2, Standee Line",["REV-PAS-STD-01"]),
q("Inspection and loading","Baggage","How must carry-on baggage be placed?","So aisles, doors, steps, and emergency exits remain clear","In front of the rear emergency door","On the driver's control area","Loose on a passenger seat during sharp turns","Baggage must be restrained and cannot interfere with movement or emergency evacuation.","Section 4.2, Baggage and Freight",["REV-PAS-INS-01"]),
q("Inspection and loading","Passenger count","Why must the driver respect the bus's rated seating and standing capacity?","Overloading harms control and evacuation safety","Extra passengers improve traction","Capacity applies only on interstate trips","Standing passengers do not count","Passenger limits protect axle loading, driver visibility, aisle access, and safe evacuation.","Section 4.2, Loading and Trip Start",["REV-PAS-LOD-01"]),
q("Inspection and loading","Door interlock","A transit bus will not move while the rear door is open. What does this indicate?","A brake-door interlock is functioning as designed","The parking brake is defective","The transmission must be in reverse","The air system has failed","Many transit buses use an interlock that applies brakes when the rear door is open; it must not be treated as a substitute for parking procedures.","Section 4.4, Prohibited Practices",["REV-PAS-PRH-02"]),
q("Inspection and loading","Accessibility equipment","Before using a wheelchair lift, what must be confirmed?","The bus is secured, the lift area is clear, and the device is operating properly","The bus is rolling slowly","Passengers stand on the lift platform","The parking brake is released","A stable vehicle and clear lift zone protect the passenger and operator during boarding.","Section 4.1, Accessibility Equipment",["REV-PAS-INS-02"]),

q("Driving and stops","Disruptive passengers","Where should a disruptive passenger be discharged if removal is necessary?","At a safe, well-lighted location where assistance is available when possible","At the nearest isolated shoulder","In an active intersection","At a railroad crossing","Passenger removal must not create a new safety hazard; the driver should follow company procedure and choose a safe place.","Section 4.3, On the Road",["REV-PAS-DRV-01"]),
q("Driving and stops","Curves","Why must a passenger bus enter curves conservatively?","Passengers have a higher center of gravity and may be standing or unbelted","Buses cannot use service brakes","Curves automatically open emergency exits","Passengers reduce rollover risk","Smooth speed control protects vehicle stability and passengers who may not be restrained.","Section 4.3, On the Road",["REV-PAS-DRV-02"]),
q("Driving and stops","Bus stops","Before pulling away from a stop, what sequence is safest?","Close doors, account for passengers, check mirrors and traffic, then signal and move","Accelerate while doors close","Rely only on the left mirror","Move first and then check the curb","A deliberate departure check prevents striking passengers, cyclists, or vehicles near the bus.","Section 4.3, At Bus Stops",["REV-PAS-DRV-03"]),
q("Driving and stops","Prohibited practices","Which action is prohibited while a passenger bus is moving?","Fueling the bus with passengers aboard in a way forbidden by the manual or local rules","Checking mirrors","Using turn signals","Maintaining following distance","Passenger-bus rules prohibit unsafe fueling, towing/pushing practices, and other operations that place riders at risk.","Section 4.4, Prohibited Practices",["REV-PAS-PRH-01"]),

q("Crossings","Railroad stop","Where should a passenger bus normally stop before railroad tracks?","Between 15 and 50 feet from the nearest rail","With the front axle on the first rail","At least 100 feet away in every case","Only after the gate begins to lower","The stop position provides sight distance without placing the bus in the track area.","Section 4.3, Railroad-highway Crossings",["REV-PAS-RRX-01"]),
q("Crossings","Railroad procedure","After stopping at a railroad crossing, what should the driver do before moving?","Open the service door or window as required, look and listen, then cross in a gear that avoids shifting","Follow the vehicle ahead without checking","Shift gears while on the tracks","Use the rear door interlock as the parking brake","The driver must actively check for trains and avoid a missed shift on the tracks.","Section 4.3, Railroad-highway Crossings",["REV-PAS-RRX-02"]),
q("Crossings","Drawbridges","When must a passenger bus stop before a drawbridge?","When there is no traffic signal or attendant controlling the bridge","Every time, even when a green signal directs traffic","Only when carrying standing passengers","Only after entering the movable span","Without active control, the driver must stop and verify the bridge is fully closed and safe.","Section 4.3, Drawbridges",["REV-PAS-DRW-01"]),
q("Crossings","Railroad clearance","Why must a bus driver check space beyond the tracks before entering?","The entire bus must clear the rails without stopping","Passengers may exit on the tracks","The gate will stay open longer","The transmission must be shifted on the crossing","Long vehicles must never enter unless enough room exists on the far side.","Section 4.3, Railroad-highway Crossings",["REV-PAS-RRX-03"]),

q("Emergencies","Evacuation decision","Which condition most strongly favors immediate bus evacuation?","Fire, smoke, or a position where the bus may be struck","A minor schedule delay","A passenger asking for fresh air","A failed interior reading light","Evacuate when remaining aboard presents greater danger than moving passengers to a safe area.","Section 4.5, Evacuation",["REV-PAS-EVA-01"]),
q("Emergencies","Evacuation control","After an evacuation begins, where should passengers be directed?","To a safe assembly area away from traffic and the bus","Directly behind the bus","Alongside leaking fuel","Into the nearest travel lane","A controlled assembly point prevents secondary injuries and allows accountability.","Section 4.5, Evacuation",["REV-PAS-EVA-02"]),

q("Qualification and rules","Endorsements","What must a driver generally complete before taking a passenger-bus skills test for the first time?","Applicable passenger knowledge testing and required entry-level training","Only a motorcycle road test","A tank endorsement test","No passenger-specific preparation","The P endorsement has specific knowledge, training, and representative-vehicle testing requirements.","Nebraska Specifics, Passenger Endorsement Requirements",["REV-PAS-QLF-01"]),
];

const school=[
q("Loading and danger zones","Danger zone","What area is included in a school bus danger zone?","The space around the bus where children may be hidden from the driver's direct view and mirrors","Only the driver's seat","Only the lane behind the bus","The area inside the passenger compartment","The danger zone extends around the bus, with the greatest risk near the front, sides, and rear where children can disappear from view.","Section 10.2, Danger Zones",["REV-SCH-DNG-01"]),
q("Loading and danger zones","Warning lights","When should alternating amber warning lights be activated for a school-bus stop?","Far enough in advance under Nebraska procedure to warn traffic before the stop","Only after the door opens","After every student is seated","While crossing railroad tracks","Advance warning gives surrounding drivers time to recognize and respond to the planned stop.","Section 10.2, Approaching the Stop",["REV-SCH-LOD-01"]),
q("Loading and danger zones","Stop position","At a route stop, how should the bus be positioned?","With the right wheels safely near the curb or road edge and the bus aligned to protect the loading area","Angled across both traffic lanes","Several feet from the curb so students enter the road","With the rear of the bus blocking a railroad crossing","A stable, predictable position reduces the distance students spend in the roadway.","Section 10.2, Loading Procedures",["REV-SCH-LOD-02"]),
q("Loading and danger zones","Student crossing","Before crossing in front of the bus, where should a student stop?","At the designated point at least 10 feet in front where the driver can see the student","Directly against the front bumper","Beside the right rear wheel","In the driver's mirror blind spot","The student must be far enough ahead to remain visible and wait for the driver's signal.","Section 10.2, Loading and Unloading",["REV-SCH-LOD-03"]),
q("Loading and danger zones","Student signal","Why must the driver give a distinct crossing signal only after checking traffic?","Students may treat the signal as permission to enter the roadway","The signal releases the parking brake","It turns off the red warning lights","It replaces student counting","The driver must first verify traffic has stopped and the crossing path is safe.","Section 10.2, Student Crossing",["REV-SCH-LOD-04"]),
q("Loading and danger zones","Dropped objects","A child drops a backpack beside the front wheel. What should the driver require?","The child should move away and get the driver's attention before retrieving it","The child should crawl under the bus quickly","The driver should move the bus forward for access","Another child should retrieve it without signaling","Children must never approach beneath or beside the bus without the driver knowing exactly where they are.","Section 10.2, Special Dangers",["REV-SCH-LOD-05"]),
q("Loading and danger zones","Counting students","After unloading, what does counting students help the driver confirm?","Every child is safely clear and no one remains in a danger zone","The route mileage is correct","The fuel level is sufficient","The mirrors no longer need to be checked","Counting complements a complete mirror sweep before the bus moves.","Section 10.2, Unloading Procedures",["REV-SCH-LOD-06"]),
q("Loading and danger zones","Backing","When students are outside the bus, what is the rule for backing?","Do not back the bus","Back only using the right mirror","Sound the horn and back quickly","Ask students to guide the bus from behind","Backing is strongly discouraged and must never occur with students outside around the bus.","Section 10.7, Backing",["REV-SCH-BCK-01"]),
q("Loading and danger zones","Post-unload sweep","Before leaving a stop, what is the final movement check?","Account for students and sweep all mirror zones, including directly in front and alongside the bus","Check only the interior mirror","Release the brake before counting","Watch only traffic behind","The bus must remain stopped until every child and traffic conflict is accounted for.","Section 10.2, Unloading Procedures",["REV-SCH-LOD-06"]),

q("Mirrors","Flat mirrors","What should properly adjusted outside flat mirrors show?","A narrow part of the bus sides plus traffic lanes behind","Only the sky","The front tires only","The entire danger zone directly under the bus","Flat mirrors provide rearward lane information and a vehicle-side reference point.","Section 10.1, Outside Left and Right Side Flat Mirrors",["REV-SCH-MIR-01"]),
q("Mirrors","Crossover mirrors","What is the main purpose of crossover mirrors?","Show the danger areas directly in front of the bus and near the front wheels","Replace every rearview mirror","Show only traffic a quarter mile behind","Monitor the passenger aisle","Crossover mirrors reveal children and objects hidden below the windshield near the front of the bus.","Section 10.1, Crossover Mirrors",["REV-SCH-MIR-01"]),

q("Crossings","Railroad stop","Where must a school bus stop at a highway-rail crossing?","Between 15 and 50 feet from the nearest rail","On the first rail","At least 200 feet away","Only after the gate lowers","The required stopping zone supports a clear look and listen without placing the bus on the tracks.","Section 10.3, Railroad-highway Crossings",["REV-SCH-RRX-01"]),
q("Crossings","Passive crossing","What makes a passive railroad crossing especially demanding?","It has no active lights or gates, so the driver must determine whether a train is approaching","It is closed to trains","It always has a flagger","The bus has the right of way without stopping","Passive crossings rely on signs and driver observation rather than automatic warnings.","Section 10.3, Passive Crossings",["REV-SCH-RRX-02"]),
q("Crossings","Multi-track crossing","After one train clears a multi-track crossing, what must the driver do?","Make sure no second train is approaching on another track before moving","Follow the train immediately","Stop the bus on the first track","Shift gears while crossing","One train can hide another, so every track must be confirmed clear.","Section 10.3, Multiple Tracks",["REV-SCH-RRX-03"]),

q("Emergencies","Evacuation decision","Which conditions require considering or beginning a school-bus evacuation?","Fire, hazardous position, or imminent danger from traffic or a train","A routine late arrival","A student requesting a seat change","A failed radio with no other hazard","The driver compares the danger of staying aboard with the danger of moving students.","Section 10.4, Emergency Evacuation",["REV-SCH-EVA-01"]),
q("Emergencies","Evacuation helpers","What job can capable student helpers perform during an evacuation?","Lead students to the assembly area and help maintain order under the driver's direction","Operate the bus on the highway","Stand in traffic to stop vehicles","Return to the bus for belongings","Assigned helpers support an orderly exit and accountability without entering new hazards.","Section 10.4, Evacuation Procedures",["REV-SCH-EVA-02"]),

q("Operations and students","Post-trip","Why must the driver walk through the bus after the route or unloading at school?","To find sleeping students, belongings, damage, and hazards before securing the bus","To avoid checking the exterior","To release the parking brake","To count traffic behind the bus","A full interior sweep ensures no child is left aboard and identifies conditions needing correction.","Section 10.2; Pupil Transportation Guide, Post-trip Inspection",["REV-SCH-PST-01","REV-PUP-01"]),
q("Operations and students","Student management","How should a serious behavior problem be handled while the bus is moving?","Stop at a safe location before addressing it","Turn around and continue driving","Brake sharply to gain attention","Ask another student to take the wheel","Vehicle control comes first; discipline should not distract the driver from the road.","Section 10.5, Student Management",["REV-SCH-OPS-01","REV-PUP-02"]),
q("Operations and students","Railroad braking","If ABS activates while braking the school bus, what should the driver do?","Maintain firm controlled brake pressure and continue steering as needed","Pump the pedal rapidly","Release the brake completely","Use only the parking brake","ABS modulates wheel pressure automatically and does not change the need for firm controlled braking.","Section 10.7, Special Safety Considerations",["REV-SCH-OPS-02"]),
q("Operations and students","Nebraska drills","How often must qualifying Nebraska pupil safe-riding instruction and evacuation drills occur?","At least twice during each school year","Once every five years","Only after a collision","Every school day","Nebraska's pupil transportation guidance calls for instruction and drills at least twice each school year.","Pupil Transportation Guide, Operating Regulations",["REV-PUP-03"]),
];

export const fourthRows={general,air,combination,passenger,school};
