"use client";

import { useEffect, useMemo, useState } from "react";
// @ts-expect-error Shared browser-safe selector is emitted as JavaScript for GitHub Pages.
import { selectQuestions } from "../content/selector.mjs";

type TestKey="general"|"air"|"combination"|"passenger"|"school";
type Mode="learn"|"exam";
type MobileScreen="home"|"tests"|"roadmap"|"scores";
type Question={id:string;test:TestKey;domain:string;topic:string;prompt:string;choices:string[];correctIndex:number;explanation:string;sourceReference:string;difficulty:"standard"|"technical";reviewRefs:string[]};
type TestDefinition={title:string;code:string;questionCount:number;poolSize:number;passCount:number;manual:string;blueprint:Record<string,number>};
type Bank={version:number;tests:Record<TestKey,TestDefinition>;questions:Question[]};
type Session={test:TestKey;mode:Mode;questionIds:string[];orders:Record<string,number[]>;answers:Record<string,number>;flagged:string[];current:number;startedAt:number};
type Attempt={id:string;test:TestKey;mode:Mode;score:number;total:number;passed:boolean;elapsed:number;completedAt:number;answers:Record<string,number>;questionIds:string[]};

const TEST_ORDER:TestKey[]=["general","air","combination","passenger","school"];
const SCREENS:{id:MobileScreen;label:string;icon:string}[]=[{id:"home",label:"Home",icon:"H"},{id:"tests",label:"Tests",icon:"T"},{id:"roadmap",label:"Roadmap",icon:"R"},{id:"scores",label:"Scores",icon:"S"}];
const SESSION_KEY="roadwise-practice-session-v2",HISTORY_KEY="roadwise-practice-history-v2";
const shuffle=<T,>(items:T[])=>{const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy};
const formatTime=(seconds:number)=>`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,"0")}`;
const percent=(attempt:Attempt)=>Math.round(attempt.score/attempt.total*100);
const routeScreen=(hash:string):MobileScreen=>({"#tests":"tests","#practice":"tests","#endorsements":"tests","#roadmap":"roadmap","#scores":"scores"}[hash] as MobileScreen)||"home";
const steps=[
  ["Choose class + work","Match Class A, B, or C and the endorsements to the Nebraska job you want."],
  ["Earn your CLP","Pass every applicable Nebraska knowledge test and receive your learner's permit."],
  ["Train + hold","Complete required ELDT and hold your Nebraska CLP for at least 14 days."],
  ["Pass in sequence","Complete inspection, basic control, then road testing in that order."],
];

function Brand(){return <a className="brand" href="#home"><span>RW</span><strong>ROADWISE<small>CDL</small></strong></a>}

export default function Home(){
  const [bank,setBank]=useState<Bank|null>(null),[done,setDone]=useState<number[]>([]),[history,setHistory]=useState<Attempt[]>([]);
  const [session,setSession]=useState<Session|null>(null),[result,setResult]=useState<Attempt|null>(null),[elapsed,setElapsed]=useState(0);
  const [hasSavedSession,setHasSavedSession]=useState(false),[mobileScreen,setMobileScreen]=useState<MobileScreen>("home"),[reviewOpen,setReviewOpen]=useState(false);

  useEffect(()=>{
    fetch("/questions.json").then(r=>{if(!r.ok)throw new Error();return r.json()}).then(setBank).catch(()=>setBank(null));
    try{setDone(JSON.parse(localStorage.getItem("roadwise-progress")||"[]"));setHistory(JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]"));setHasSavedSession(Boolean(localStorage.getItem(SESSION_KEY)))}catch{}
    const sync=()=>setMobileScreen(routeScreen(location.hash));sync();addEventListener("hashchange",sync);return()=>removeEventListener("hashchange",sync);
  },[]);
  useEffect(()=>{if(!session)return;localStorage.setItem(SESSION_KEY,JSON.stringify(session));setElapsed(Math.floor((Date.now()-session.startedAt)/1000));const id=setInterval(()=>setElapsed(Math.floor((Date.now()-session.startedAt)/1000)),1000);return()=>clearInterval(id)},[session]);
  useEffect(()=>{const back=()=>{if(session&&location.hash!=="#quiz"){setHasSavedSession(true);setSession(null);setReviewOpen(false)}if(result&&location.hash!=="#results")setResult(null)};addEventListener("hashchange",back);return()=>removeEventListener("hashchange",back)},[session,result]);

  const questionsById=useMemo(()=>new Map((bank?.questions||[]).map(q=>[q.id,q])),[bank]);
  const current=session?questionsById.get(session.questionIds[session.current]):null,average=history.length?Math.round(history.reduce((sum,item)=>sum+percent(item),0)/history.length):null,recent=history[0]||null;
  const bestScores=useMemo(()=>Object.fromEntries(TEST_ORDER.map(key=>{const attempts=history.filter(item=>item.test===key&&item.mode==="exam");return[key,attempts.length?Math.max(...attempts.map(percent)):null]})) as Record<TestKey,number|null>,[history]);
  const weakTopics=useMemo(()=>{if(!bank)return[] as [string,number][];const misses=new Map<string,number>();history.slice(0,10).forEach(item=>item.questionIds.forEach(id=>{const q=questionsById.get(id);if(q&&item.answers[id]!==q.correctIndex)misses.set(q.topic,(misses.get(q.topic)||0)+1)}));return[...misses.entries()].sort((a,b)=>b[1]-a[1]).slice(0,3)},[bank,history,questionsById]);
  const technicalAccuracy=useMemo(()=>{let correct=0,total=0;history.forEach(item=>item.questionIds.forEach(id=>{const q=questionsById.get(id);if(q?.difficulty==="technical"){total+=1;if(item.answers[id]===q.correctIndex)correct+=1}}));return total?{correct,total,percent:Math.round(correct/total*100)}:null},[history,questionsById]);

  const navigate=(screen:MobileScreen)=>{setMobileScreen(screen);location.hash=screen};
  const toggleStep=(index:number)=>{const next=done.includes(index)?done.filter(x=>x!==index):[...done,index];setDone(next);localStorage.setItem("roadwise-progress",JSON.stringify(next))};
  const start=(test:TestKey,mode:Mode)=>{if(!bank)return;const definition=bank.tests[test],chosen=selectQuestions({questions:bank.questions,test,count:mode==="learn"?10:definition.questionCount,history,blueprint:definition.blueprint}) as Question[];setResult(null);setHasSavedSession(true);setReviewOpen(false);setSession({test,mode,questionIds:chosen.map(q=>q.id),orders:Object.fromEntries(chosen.map(q=>[q.id,shuffle([0,1,2,3])])),answers:{},flagged:[],current:0,startedAt:Date.now()});location.hash="quiz"};
  const resume=()=>{try{const saved=JSON.parse(localStorage.getItem(SESSION_KEY)||"null");if(saved){setResult(null);setReviewOpen(false);setSession(saved);location.hash="quiz"}}catch{}};
  const select=(answer:number)=>{if(!session||!current||(session.mode==="learn"&&session.answers[current.id]!==undefined))return;setSession({...session,answers:{...session.answers,[current.id]:answer}})};
  const move=(index:number)=>{if(session){setReviewOpen(false);setSession({...session,current:Math.max(0,Math.min(session.questionIds.length-1,index))})}};
  const toggleFlag=()=>{if(!session||!current)return;setSession({...session,flagged:session.flagged.includes(current.id)?session.flagged.filter(x=>x!==current.id):[...session.flagged,current.id]})};
  const submit=()=>{if(!session||!bank)return;const unanswered=session.questionIds.length-Object.keys(session.answers).length;if(unanswered&&!confirm(`${unanswered} question${unanswered===1?" is":"s are"} unanswered. Submit anyway?`))return;const score=session.questionIds.filter(id=>session.answers[id]===questionsById.get(id)?.correctIndex).length,attempt:Attempt={id:`${Date.now()}`,test:session.test,mode:session.mode,score,total:session.questionIds.length,passed:score>=Math.ceil(session.questionIds.length*.8),elapsed:Math.floor((Date.now()-session.startedAt)/1000),completedAt:Date.now(),answers:session.answers,questionIds:session.questionIds},next=[attempt,...history].slice(0,50);setHistory(next);localStorage.setItem(HISTORY_KEY,JSON.stringify(next));localStorage.removeItem(SESSION_KEY);setHasSavedSession(false);setResult(attempt);setSession(null);setReviewOpen(false);location.hash="results"};
  const quit=()=>{if(confirm("Leave this test? Your answers will stay saved so you can resume later.")){setHasSavedSession(true);setSession(null);setReviewOpen(false);navigate("tests")}};
  const clearHistory=()=>{if(confirm("Clear saved test scores? Your CDL roadmap progress will not be erased.")){setHistory([]);localStorage.removeItem(HISTORY_KEY)}};
  const leaveResults=()=>{setResult(null);navigate("tests")};

  const testCards=(mobile=false)=>!bank?<div className="loadingCard" role="status">Loading the CDL question bank...</div>:<div className={mobile?"mobileTestList":"testLaneGrid"}>{TEST_ORDER.map((key,index)=>{const d=bank.tests[key],best=bestScores[key];return <article className={mobile?"mobileTestCard":`testLane ${index<2?"core":"compact"}`} key={key}>{!mobile&&index<2&&<div className="laneBand">LANE 0{index+1} | {index===0?"CORE LICENSE":"VEHICLE SYSTEMS"}</div>}<div className="laneBody"><span className="roundCode">{d.code}</span><div><h3>{d.title}</h3><p>{d.questionCount}-question exam from a pool of {d.poolSize}</p></div></div><div className="laneMeta">{best===null?`Pass with ${d.passCount}`:`Best score ${best}%`}</div><div className="laneActions"><button className="exam" onClick={()=>start(key,"exam")}>FULL EXAM</button><button onClick={()=>start(key,"learn")}>LEARN 10</button></div></article>})}</div>;

  return <main className="siteCanvas" id="top"><div className={`appFrame ${session||result?"focusMode":""}`}>
    <div className="desktopExperience"><aside className="sideRail"><Brand/><nav aria-label="Primary navigation"><a className="active" href="#top"><i/>My dashboard</a><a href="#practice">Practice tests</a><a href="#roadmap">Study roadmap</a><a href="#scores">Score history</a><a href="#endorsements">Endorsements</a></nav><section className="railGoal"><p>CURRENT GOAL</p><h2>Class B + P/S</h2><span>School bus route</span><div className="railBar"><i style={{width:`${done.length*25}%`}}/></div><small>{done.length} of 4 steps</small></section><section className="railStatus"><b>NEBRASKA 2026</b><span>540 questions</span><small>Works offline</small></section></aside>
      <div className="workspace"><header className="topBar"><div className="greeting"><small>GOOD MORNING,</small><strong>JOSHUA</strong></div><nav><a href="#sources">Manual</a><a href="#roadmap">Nebraska roadmap</a></nav><a className="orangeButton" href="#practice">TAKE A TEST</a><span className="avatar">JE</span></header>
      {!session&&!result&&<><section className="routeHero"><div className="routeIntro"><p>YOUR ROAD TO A NEBRASKA CDL</p><h1>PICK YOUR ROUTE.<br/><em>BUILD YOUR SCORE.</em></h1><span>A clear path from permit study to skills testing.</span><div>{hasSavedSession?<button className="orangeButton" onClick={resume}>RESUME EXAM</button>:<button className="orangeButton" onClick={()=>start("general","learn")}>START A DRILL</button>}<small>{hasSavedSession?"Saved session ready":"540 questions ready"}</small></div></div><div className="routeTrack">{steps.map((step,index)=><div className={done.includes(index)?"complete":index===done.length?"current":""} key={step[0]}><span>{index+1}</span><b>{["CHOOSE","CLP TESTS","TRAIN","SKILLS"][index]}</b></div>)}</div><div className="scoreSign"><small>YOUR SCORE ROUTE</small><strong>{average===null?"--":`${average}%`}</strong><span>AVERAGE SCORE</span><i><b style={{width:`${average||0}%`}}/></i></div></section>
      <section className="dashboardGrid" id="practice"><div className="primaryColumn"><h2>Recommended next step</h2><article className="recommendCard"><span className="roundCode">GK</span><div><small>STEP 2 OF 4</small><h3>Pass General Knowledge</h3><p>Your drills build toward the full 50-question exam. Review weak topics, then test when ready.</p></div><button onClick={()=>start("general","learn")}>CONTINUE ROUTE</button></article><div className="laneHeading"><h2>Choose a test lane</h2><span>Balanced pools with fewer repeats</span></div>{testCards()}<div className="testingNote">General Knowledge comes before the other Nebraska written CDL tests. These are original practice questions, not official DMV exam items.</div></div><aside className="insights" id="roadmap"><h2>Your progress</h2><section className="progressCard"><small>NEBRASKA ROADMAP</small><h3>{done.length} of 4 milestones complete</h3><div className="progressDots">{steps.map((step,index)=><button key={step[0]} className={done.includes(index)?"complete":index===done.length?"current":""} onClick={()=>toggleStep(index)}>{index+1}</button>)}</div><p>Current: {steps[Math.min(done.length,3)][0]}</p></section><div className="statPair"><section><small>THIS WEEK</small><strong>{history.length}</strong><span>saved attempts</span></section><section><small>AVERAGE SCORE</small><strong>{average===null?"--":`${average}%`}</strong><span className={average!==null&&average>=80?"good":""}>{average===null?"Complete a test":average>=80?"Above passing target":"Keep studying"}</span></section></div><section className="latestReport" id="scores"><h2>Latest road report</h2>{recent?<div><small>{bank?.tests[recent.test]?.title||recent.test}</small><p>{recent.score} of {recent.total} correct</p><strong className={recent.passed?"good":""}>{percent(recent)}%</strong><b>{recent.passed?"PASS":"REVIEW"}</b></div>:<p className="emptyReport">Your latest completed test will appear here.</p>}{history.length>0&&<><details className="historyPanel"><summary>View recent scores</summary>{history.slice(0,5).map(item=><p key={item.id}><span>{bank?.tests[item.test]?.title}</span><b>{percent(item)}%</b></p>)}</details><button className="clearButton" onClick={clearHistory}>Clear score history</button></>}</section><section className="sourceDesk" id="sources"><small>PRIMARY SOURCE</small><p>Nebraska Modified CDL Driver's Manual - March 2026</p><small>SUPPLEMENTAL</small><p>Nebraska Pupil Transportation Guide - August 2019</p></section></aside></section></>}</div></div>

    {!session&&!result&&<section className="mobileAppShell" aria-label="Roadwise mobile app"><header className="mobileAppHeader"><Brand/><div><small>{mobileScreen==="home"?"GOOD MORNING, JOSHUA":SCREENS.find(item=>item.id===mobileScreen)?.label.toUpperCase()}</small><strong>{mobileScreen==="home"?"Ready for the road?":"ROADWISE CDL"}</strong></div><span className="avatar">JE</span></header><div className="mobileScreenViewport">
      <section className="mobileScreen mobileHome" hidden={mobileScreen!=="home"}><div className="mobileRouteHero"><p>YOUR ROAD TO A NEBRASKA CDL</p><h1>PICK YOUR ROUTE.<br/><em>BUILD YOUR SCORE.</em></h1><div className="mobileScore"><span>AVERAGE</span><strong>{average===null?"--":`${average}%`}</strong></div></div>{hasSavedSession&&<article className="mobileResume"><div><small>SAVED SESSION</small><h2>Continue where you stopped</h2><p>Your answers and flagged questions are ready.</p></div><button onClick={resume}>RESUME</button></article>}<article className="mobileNext"><small>RECOMMENDED NEXT STEP</small><div><span className="roundCode">GK</span><div><h2>Pass General Knowledge</h2><p>Build confidence with a balanced 10-question drill.</p></div></div><button onClick={()=>start("general","learn")}>START LEARN 10</button></article><div className="mobileHomeStats"><article><small>ROADMAP</small><strong>{done.length}/4</strong><span>milestones</span></article><article><small>ATTEMPTS</small><strong>{history.length}</strong><span>saved locally</span></article></div><button className="mobileLinkButton" onClick={()=>navigate("tests")}>View all practice tests <span>-&gt;</span></button></section>
      <section className="mobileScreen mobileTests" hidden={mobileScreen!=="tests"}><div className="mobileScreenHeading"><p>PRACTICE CENTER</p><h1>Choose your test</h1><span>Balanced pools with fewer repeats.</span></div>{testCards(true)}<p className="mobileInfoNote">General Knowledge comes before the other applicable Nebraska written CDL tests.</p></section>
      <section className="mobileScreen mobileRoadmap" hidden={mobileScreen!=="roadmap"}><div className="mobileScreenHeading"><p>NEBRASKA CDL PATH</p><h1>Your roadmap</h1><span>Tap a milestone when you complete it.</span></div><div className="mobileMilestones">{steps.map((step,index)=><button key={step[0]} className={`${done.includes(index)?"complete":""} ${index===done.length?"current":""}`} onClick={()=>toggleStep(index)}><i>{done.includes(index)?"OK":index+1}</i><span><b>{step[0]}</b><small>{step[1]}</small></span></button>)}</div><article className="mobileGoalCard"><small>CURRENT GOAL</small><h2>Class B + P/S</h2><p>School bus route</p><div><i style={{width:`${done.length*25}%`}}/></div><span>{done.length} of 4 steps complete</span></article><div className="mobileResources"><h2>Official resources</h2><a href="https://dmv.nebraska.gov/driver-manuals-practice-tests" target="_blank" rel="noreferrer"><b>Nebraska CDL manual</b><span>March 2026 edition -&gt;</span></a><a href="https://dmv.nebraska.gov/manuals" target="_blank" rel="noreferrer"><b>Pupil transportation handbook</b><span>Nebraska DMV manuals -&gt;</span></a></div><div className="mobileOffline"><b>540 questions ready offline</b><span>Progress stays private on this device.</span></div></section>
      <section className="mobileScreen mobileScores" hidden={mobileScreen!=="scores"}><div className="mobileScreenHeading"><p>YOUR ROAD REPORT</p><h1>Scores and progress</h1><span>See what to study next.</span></div><div className="mobileScoreSummary"><article><small>AVERAGE</small><strong>{average===null?"--":`${average}%`}</strong><span>{average!==null&&average>=80?"Passing range":"80% is passing"}</span></article><article><small>TECHNICAL</small><strong>{technicalAccuracy?`${technicalAccuracy.percent}%`:"--"}</strong><span>{technicalAccuracy?`${technicalAccuracy.correct} of ${technicalAccuracy.total} correct`:"Start a test"}</span></article></div><section className="mobileBest"><h2>Best exam scores</h2>{TEST_ORDER.map(key=><div key={key}><span>{bank?.tests[key]?.title||key}</span><b>{bestScores[key]===null?"Not taken":`${bestScores[key]}%`}</b></div>)}</section><section className="mobileWeak"><h2>Study next</h2>{weakTopics.length?weakTopics.map(([topic,count])=><div key={topic}><span>{topic}</span><b>{count} missed</b></div>):<p>Complete a practice test to discover weak topics.</p>}</section><section className="mobileRecent"><h2>Recent attempts</h2>{history.length?history.slice(0,8).map(item=><article key={item.id}><div><b>{bank?.tests[item.test]?.title||item.test}</b><span>{item.mode==="exam"?"Full exam":"Learn drill"} | {new Date(item.completedAt).toLocaleDateString()}</span></div><strong className={item.passed?"good":""}>{percent(item)}%</strong></article>):<p>No completed attempts yet.</p>}</section>{history.length>0&&<button className="mobileClear" onClick={clearHistory}>Clear score history</button>}</section>
    </div><nav className="mobileAppNav">{SCREENS.map(item=><button key={item.id} className={mobileScreen===item.id?"active":""} onClick={()=>navigate(item.id)} aria-current={mobileScreen===item.id?"page":undefined}><i>{item.icon}</i><span>{item.label}</span></button>)}</nav></section>}

    {session&&current&&bank&&<section className="focusPanel"><section className="runner"><header><button className="plain" onClick={quit}>Exit</button><div><b>{bank.tests[session.test].title}</b><span>{session.mode==="exam"?"FULL EXAM":"LEARN MODE"} | {formatTime(elapsed)}</span></div><button className={`flag ${session.flagged.includes(current.id)?"active":""}`} onClick={toggleFlag}>{session.flagged.includes(current.id)?"Flagged":"Flag"}</button></header><div className="runnerProgress"><span style={{width:`${Object.keys(session.answers).length/session.questionIds.length*100}%`}}/><b>{Object.keys(session.answers).length} of {session.questionIds.length} answered</b></div><button className="mobileReviewToggle" onClick={()=>setReviewOpen(!reviewOpen)} aria-expanded={reviewOpen}>Question {session.current+1} of {session.questionIds.length} | {reviewOpen?"Close review":"Review questions"}</button><div className={`questionLayout ${reviewOpen?"reviewOpen":""}`}><aside>{session.questionIds.map((id,i)=><button key={id} className={`${i===session.current?"current":""} ${session.answers[id]!==undefined?"answered":""} ${session.flagged.includes(id)?"marked":""}`} onClick={()=>move(i)}>{i+1}</button>)}</aside><article className="questionCard"><p className="questionMeta">QUESTION {session.current+1} OF {session.questionIds.length} | {current.topic} {current.difficulty==="technical"&&<span className="technicalTag">TECHNICAL</span>}</p><h2>{current.prompt}</h2><div className="answerList">{session.orders[current.id].map((answer,index)=>{const chosen=session.answers[current.id]===answer,revealed=session.mode==="learn"&&session.answers[current.id]!==undefined,correct=revealed&&answer===current.correctIndex,wrong=revealed&&chosen&&!correct;return <button key={answer} className={`${chosen?"selected":""} ${correct?"correct":""} ${wrong?"wrong":""}`} onClick={()=>select(answer)}><span>{String.fromCharCode(65+index)}</span>{current.choices[answer]}</button>})}</div>{session.mode==="learn"&&session.answers[current.id]!==undefined&&<div className="explanation"><b>{session.answers[current.id]===current.correctIndex?"Correct":"Review this one"}</b><p>{current.explanation}</p><small>Source: {current.sourceReference}</small></div>}<footer className="questionFooter"><button disabled={session.current===0} onClick={()=>move(session.current-1)}>Previous</button>{session.current===session.questionIds.length-1?<button className="submit" onClick={submit}>Submit</button>:<button className="nextQuestion" onClick={()=>move(session.current+1)}>Next</button>}</footer></article></div></section></section>}
    {result&&bank&&<section className="focusPanel"><section className="resultPanel"><p className="eyebrow blue">{result.mode==="exam"?"EXAM RESULTS":"LEARN RESULTS"}</p><div className={`scoreSeal ${result.passed?"passed":""}`}><strong>{percent(result)}%</strong><span>{result.passed?"PASS":"KEEP STUDYING"}</span></div><h2>{bank.tests[result.test].title}</h2><p>{result.score} of {result.total} correct | {formatTime(result.elapsed)}</p>{(()=>{const technical=result.questionIds.map(id=>questionsById.get(id)).filter(q=>q?.difficulty==="technical"),correct=technical.filter(q=>result.answers[q!.id]===q!.correctIndex).length;return technical.length?<p className="technicalResult"><b>Technical accuracy:</b> {correct} of {technical.length} ({Math.round(correct/technical.length*100)}%)</p>:null})()}<div className="resultActions"><button className="orangeButton" onClick={()=>start(result.test,result.mode)}>Try again</button><button onClick={leaveResults}>All practice tests</button></div>{result.questionIds.some(id=>result.answers[id]!==questionsById.get(id)?.correctIndex)&&<div className="review"><h3>Review missed questions</h3>{result.questionIds.filter(id=>result.answers[id]!==questionsById.get(id)?.correctIndex).map(id=>{const q=questionsById.get(id)!;return <article key={id}><b>{q.topic}</b><h4>{q.prompt}</h4><p><span>Correct answer:</span> {q.choices[q.correctIndex]}</p><p>{q.explanation}</p><small>Source: {q.sourceReference}</small></article>})}</div>}</section></section>}
  </div></main>
}
