"use client";

import { type ChangeEvent, type FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { selectQuestions } from "../content/selector.mjs";
import { STUDY_ROUTES, domainPerformance, dueReviewIds, nextRecommendation, readinessForTest, reviewQuestion, routeTests, selectAdaptiveQuestions } from "../content/study-engine.mjs";

type TestKey="general"|"air"|"combination"|"passenger"|"school";
type View="home"|"study"|"tests"|"progress"|"settings";
type StudyKind="quick"|"learn"|"adaptive"|"review"|"exam";
type RouteKey="class-a"|"class-b"|"passenger"|"school";
type Question={id:string;test:TestKey;domain:string;topic:string;prompt:string;choices:string[];correctIndex:number;explanation:string;sourceReference:string;sourceIds:string[];difficulty:"standard"|"technical";reviewRefs:string[]};
type TestDefinition={title:string;code:string;questionCount:number;poolSize:number;passCount:number;manual:string;blueprint:Record<string,number>};
type Bank={version:number;tests:Record<TestKey,TestDefinition>;manuals:Record<string,{title:string;edition:string;officialUrl:string;totalPages:number}>;sources:Record<string,{manualId:string;section:string;pdfPage:number;printedPage:string;studySummary:string}>;questions:Question[]};
type Profile={name:string;route:RouteKey;airBrakes:boolean;weeklyTarget:number};
type ReviewItem={stage:number;dueAt:number;correctStreak:number;lastAnsweredAt:number};
type Session={test:TestKey;kind:StudyKind;questionIds:string[];orders:Record<string,number[]>;answers:Record<string,number>;flagged:string[];current:number;startedAt:number};
type Attempt={id:string;test:TestKey;mode:"learn"|"exam";kind?:StudyKind;score:number;total:number;passed:boolean;elapsed:number;completedAt:number;answers:Record<string,number>;questionIds:string[]};
type RoadwiseState={schemaVersion:3;profile:Profile|null;attempts:Attempt[];roadmap:number[];reviewSchedule:Record<string,ReviewItem>;activity:string[];activeSession:Session|null;settings:{reducedMotion:boolean}};
type Ready=ReturnType<typeof readinessForTest>;

const STATE_KEY="roadwise-state-v3",OLD_HISTORY_KEY="roadwise-practice-history-v2",OLD_SESSION_KEY="roadwise-practice-session-v2";
const TEST_ORDER:TestKey[]=["general","air","combination","passenger","school"];
const NAV:{id:View;label:string;icon:string}[]=[{id:"home",label:"Home",icon:"H"},{id:"study",label:"Study",icon:"S"},{id:"tests",label:"Tests",icon:"T"},{id:"progress",label:"Progress",icon:"P"},{id:"settings",label:"Settings",icon:"G"}];
const EMPTY_STATE:RoadwiseState={schemaVersion:3,profile:null,attempts:[],roadmap:[],reviewSchedule:{},activity:[],activeSession:null,settings:{reducedMotion:false}};
const shuffle=<T,>(items:T[])=>{const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy};
const percent=(attempt:Attempt)=>Math.round(attempt.score/attempt.total*100);
const formatTime=(seconds:number)=>`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,"0")}`;
const dayKey=(value=Date.now())=>new Date(value).toISOString().slice(0,10);
const pretty=(value:string)=>value.replace(/[-_]/g," ").replace(/\b\w/g,letter=>letter.toUpperCase());

function migrateState():RoadwiseState{
  try{const saved=JSON.parse(localStorage.getItem(STATE_KEY)||"null");if(saved?.schemaVersion===3)return{...EMPTY_STATE,...saved,settings:{...EMPTY_STATE.settings,...saved.settings}}}catch{}
  let attempts:Attempt[]=[],activeSession:Session|null=null,roadmap:number[]=[],name="";
  try{attempts=JSON.parse(localStorage.getItem(OLD_HISTORY_KEY)||"[]")}catch{}
  try{const savedSession=JSON.parse(localStorage.getItem(OLD_SESSION_KEY)||"null");activeSession=savedSession?{...savedSession,kind:savedSession.kind||(savedSession.mode==="exam"?"exam":"learn")}:null}catch{}
  try{roadmap=JSON.parse(localStorage.getItem("roadwise-progress")||"[]")}catch{}
  try{name=(localStorage.getItem("roadwise-user-name")||"").trim()}catch{}
  return{...EMPTY_STATE,attempts,activeSession,roadmap,profile:name?{name,route:"school",airBrakes:true,weeklyTarget:4}:null};
}

type SharedProps={bank:Bank;state:RoadwiseState;profile:Profile;goalTests:TestKey[];dueIds:string[];readiness:Record<TestKey,Ready>|null;questionsById:Map<string,Question>;startStudy:(test:TestKey,kind:StudyKind)=>void;navigate:(view:View)=>void};

function ScreenHeader({eyebrow,title,description,aside}:{eyebrow:string;title:string;description:string;aside?:React.ReactNode}){
  return <header className="screenHeader"><div><p>{eyebrow}</p><h1>{title}</h1><span>{description}</span></div>{aside}</header>;
}

function HomeScreen(props:SharedProps&{recommendation:any;runRecommendation:()=>void;average:number|null;weekDays:number;updateReady:boolean;applyUpdate:()=>void}){
  const{bank,profile,goalTests,dueIds,readiness,startStudy,navigate,recommendation,runRecommendation,weekDays,updateReady,applyUpdate}=props,route=STUDY_ROUTES[profile.route];
  return <div className="screen homeScreen"><ScreenHeader eyebrow={`GOOD ${new Date().getHours()<12?"MORNING":new Date().getHours()<18?"AFTERNOON":"EVENING"}, ${profile.name.toUpperCase()}`} title="Ready for the road?" description={`${route.title} study route · ${weekDays} of ${profile.weeklyTarget} study days this week`} aside={<div className="routeBadge"><small>CURRENT ROUTE</small><b>{route.title}</b></div>}/>
    {updateReady&&<div className="updateBanner"><span>A fresh Roadwise update is ready.</span><button onClick={applyUpdate}>UPDATE NOW</button></div>}
    <section className="todayCard"><div><p>RECOMMENDED NEXT</p><h2>{recommendation?.label}</h2><span>{recommendation?.kind==="resume"?"Your answers and flagged questions are waiting.":dueIds.length?"Roadwise is prioritizing material ready for review.":"Built from your route, recent scores, and topic performance."}</span></div><button onClick={runRecommendation}>{recommendation?.kind==="resume"?"RESUME":"START"}</button></section>
    <section className="homeGrid"><article className="readinessCard"><div className="sectionTitle"><div><p>ROUTE READINESS</p><h2>Your test path</h2></div><button onClick={()=>navigate("progress")}>DETAILS</button></div><div className="routeTests">{goalTests.map((test,index)=>{const item=readiness?.[test];return <button key={test} onClick={()=>navigate("tests")}><i className={item?.ready?"ready":item?.enoughData?"building":""}>{item?.ready?"OK":index+1}</i><span><b>{bank.tests[test].title}</b><small>{item?.ready?"Ready":item?.score!==null?`${item?.score}% recent average`:"Start studying"}</small></span></button>})}</div></article>
      <article className="weekCard"><p>THIS WEEK</p><strong>{weekDays}/{profile.weeklyTarget}</strong><span>study days</span><div>{Array.from({length:7},(_,index)=><i className={index<weekDays?"done":""} key={index}/>)}</div></article>
      <article className="reviewCard"><p>MISTAKE REVIEW</p><strong>{dueIds.length}</strong><span>{dueIds.length===1?"question due":"questions due"}</span><button onClick={()=>navigate("study")}>OPEN REVIEW</button></article></section>
    <section className="quickActions"><div className="sectionTitle"><div><p>QUICK START</p><h2>Choose how to study</h2></div></div><div><button onClick={()=>startStudy(recommendation?.test||"general","quick")}><i>5</i><span><b>Quick 5</b><small>A short daily tune-up</small></span></button><button onClick={()=>startStudy(recommendation?.test||"general","learn")}><i>10</i><span><b>Learn 10</b><small>Adaptive practice with explanations</small></span></button><button onClick={()=>navigate("tests")}><i>80%</i><span><b>Full exams</b><small>Nebraska-style test lengths</small></span></button></div></section>
  </div>;
}

function StudyScreen(props:SharedProps){
  const{bank,state,dueIds,readiness,questionsById,startStudy}=props;
  const weak=TEST_ORDER.flatMap(test=>Object.entries(domainPerformance({attempts:state.attempts,questionsById,test})).map(([domain,value]:any)=>({test,domain,...value}))).sort((a,b)=>a.percent-b.percent).slice(0,5);
  return <div className="screen"><ScreenHeader eyebrow="ADAPTIVE STUDY" title="Practice what matters next." description="Roadwise mixes weak topics, due mistakes, under-seen material, and technical questions."/>
    <section className="studySpotlight"><div><small>DUE NOW</small><strong>{dueIds.length}</strong><span>mistake-review questions</span></div><div><h2>{dueIds.length?"Clear your review queue":"Your review queue is clear"}</h2><p>{dueIds.length?"Correct answers move farther apart. Misses return sooner.":"Start an adaptive drill to keep building mastery."}</p></div><button disabled={!dueIds.length} onClick={()=>startStudy((questionsById.get(dueIds[0])?.test||"general")as TestKey,"review")}>REVIEW NOW</button></section>
    <div className="sectionTitle"><div><p>BY SUBJECT</p><h2>Adaptive drills</h2></div></div><div className="studySubjectGrid">{TEST_ORDER.map(test=>{const testDue=dueIds.filter(id=>questionsById.get(id)?.test===test).length,item=readiness?.[test];return <article key={test}><span className="testCode">{bank.tests[test].code}</span><div><h3>{bank.tests[test].title}</h3><p>{testDue?`${testDue} due for review`:item?.weakest!==null&&item?.weakest!==undefined?`Weakest domain ${item.weakest}%`:"Build your baseline"}</p></div><button onClick={()=>startStudy(test,"learn")}>LEARN 10</button><button className="secondary" onClick={()=>startStudy(test,"quick")}>QUICK 5</button></article>})}</div>
    <section className="weakTopics"><div className="sectionTitle"><div><p>FOCUS AREAS</p><h2>Lowest recent domains</h2></div></div>{weak.length?weak.map(item=><button key={`${item.test}-${item.domain}`} onClick={()=>startStudy(item.test as TestKey,"adaptive")}><span><b>{pretty(item.domain)}</b><small>{bank.tests[item.test as TestKey].title} · {item.total} answered</small></span><strong>{item.percent}%</strong></button>):<p className="emptyState">Complete a drill and Roadwise will identify the topics that need attention.</p>}</section>
  </div>;
}

function TestsScreen({bank,state,goalTests,readiness,startStudy}:SharedProps){
  return <div className="screen"><ScreenHeader eyebrow="PRACTICE CENTER" title="Choose a test." description="Every subject stays open. Your selected route is marked for quick recognition."/><div className="testHubGrid">{TEST_ORDER.map(test=>{const definition=bank.tests[test],item=readiness?.[test],attempts=state.attempts.filter(attempt=>attempt.test===test),best=attempts.length?Math.max(...attempts.map(percent)):null;return <article key={test} className={goalTests.includes(test)?"onRoute":""}><header><span className="testCode">{definition.code}</span>{goalTests.includes(test)&&<small>ON YOUR ROUTE</small>}</header><h2>{definition.title}</h2><p>{definition.questionCount}-question exam from a {definition.poolSize}-question pool</p><div className="testStats"><span><small>READINESS</small><b>{item?.ready?"READY":item?.score!==null?`${item?.score}%`:"BUILDING"}</b></span><span><small>BEST</small><b>{best===null?"--":`${best}%`}</b></span><span><small>PASS</small><b>{definition.passCount}/{definition.questionCount}</b></span></div><div className="testActions"><button onClick={()=>startStudy(test,"learn")}>LEARN 10</button><button className="secondary" onClick={()=>startStudy(test,"exam")}>FULL EXAM</button></div></article>})}</div><p className="legalNote">General Knowledge comes before other applicable Nebraska written CDL tests. Roadwise provides original manual-grounded practice, not official examination items.</p></div>;
}

function ProgressScreen({bank,state,readiness,startStudy,average}:SharedProps&{average:number|null}){
  const due=Object.values(state.reviewSchedule).filter(item=>item.dueAt<=Date.now()).length;
  return <div className="screen"><ScreenHeader eyebrow="YOUR ROAD REPORT" title="Progress you can act on." description="Readiness uses full-exam consistency and performance across every domain." aside={<div className="averageBadge"><small>ALL PRACTICE</small><b>{average===null?"--":`${average}%`}</b></div>}/><section className="progressSummary"><article><small>STUDY DAYS</small><strong>{state.activity.length}</strong><span>total active days</span></article><article><small>ATTEMPTS</small><strong>{state.attempts.length}</strong><span>drills and exams</span></article><article><small>DUE REVIEW</small><strong>{due}</strong><span>questions ready</span></article></section><div className="progressTestList">{TEST_ORDER.map(test=>{const item=readiness?.[test],domains=Object.entries(item?.domains||{});return <article key={test}><header><div><span className="testCode">{bank.tests[test].code}</span><div><h2>{bank.tests[test].title}</h2><p>{item?.ready?"Ready for your next step":item?.enoughData?"Keep strengthening weak domains":"Complete two full exams to establish readiness"}</p></div></div><strong className={item?.ready?"ready":""}>{item?.ready?"READY":item?.score!==null?`${item?.score}%`:"--"}</strong></header><div className="domainBars">{domains.length?domains.map(([domain,value]:any)=><div key={domain}><span>{pretty(domain)}</span><i><b style={{width:`${value.percent}%`}}/></i><strong>{value.percent}%</strong></div>):<p>No domain data yet.</p>}</div><button onClick={()=>startStudy(test,item?.ready?"exam":"adaptive")}>{item?.ready?"TAKE ANOTHER EXAM":"STUDY THIS TEST"}</button></article>})}</div><section className="attemptHistory"><div className="sectionTitle"><div><p>HISTORY</p><h2>Recent attempts</h2></div></div>{state.attempts.length?state.attempts.slice(0,12).map(attempt=><div key={attempt.id}><span><b>{bank.tests[attempt.test].title}</b><small>{attempt.mode==="exam"?"Full exam":attempt.kind==="quick"?"Quick 5":"Study drill"} · {new Date(attempt.completedAt).toLocaleDateString()}</small></span><strong className={attempt.passed?"pass":""}>{percent(attempt)}%</strong></div>):<p className="emptyState">Your completed practice will appear here.</p>}</section></div>;
}


function Brand(){return <div className="brand"><span>RW</span><div><b>ROADWISE</b><small>CDL</small></div></div>}

export default function Home(){
  const[bank,setBank]=useState<Bank|null>(null),[state,setState]=useState<RoadwiseState|null>(null),[view,setView]=useState<View>("home"),[result,setResult]=useState<Attempt|null>(null);
  const[reviewFilter,setReviewFilter]=useState<"all"|"missed">("missed"),[sourceQuestion,setSourceQuestion]=useState<Question|null>(null),[online,setOnline]=useState(true),[elapsed,setElapsed]=useState(0);
  const[importMessage,setImportMessage]=useState(""),[updateReady,setUpdateReady]=useState(false),[editingProfile,setEditingProfile]=useState(false),[showSession,setShowSession]=useState(false);
  const dialogRef=useRef<HTMLDialogElement>(null),importRef=useRef<HTMLInputElement>(null),swRef=useRef<ServiceWorkerRegistration|null>(null);

  useEffect(()=>{
    fetch("./questions.json").then(response=>{if(!response.ok)throw new Error();return response.json()}).then(setBank).catch(()=>setBank(null));
    setState(migrateState());const hash=location.hash.slice(1) as View;if(NAV.some(item=>item.id===hash))setView(hash);
    const sync=()=>setOnline(navigator.onLine);sync();addEventListener("online",sync);addEventListener("offline",sync);
    if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").then(registration=>{swRef.current=registration;if(registration.waiting)setUpdateReady(true);registration.addEventListener("updatefound",()=>registration.installing?.addEventListener("statechange",()=>{if(registration.waiting)setUpdateReady(true)}))}).catch(()=>{}),{once:true});
    return()=>{removeEventListener("online",sync);removeEventListener("offline",sync)};
  },[]);
  useEffect(()=>{if(state)try{localStorage.setItem(STATE_KEY,JSON.stringify(state))}catch{}},[state]);
  useEffect(()=>{if(!state?.activeSession)return;setElapsed(Math.floor((Date.now()-state.activeSession.startedAt)/1000));const timer=setInterval(()=>setElapsed(Math.floor((Date.now()-state.activeSession!.startedAt)/1000)),1000);return()=>clearInterval(timer)},[state?.activeSession]);
  useEffect(()=>{const dialog=dialogRef.current;if(!dialog)return;if(sourceQuestion&&!dialog.open)dialog.showModal();if(!sourceQuestion&&dialog.open)dialog.close()},[sourceQuestion]);
  useEffect(()=>{document.documentElement.dataset.reduceMotion=state?.settings.reducedMotion?"true":"false"},[state?.settings.reducedMotion]);

  const questionsById=useMemo(()=>new Map((bank?.questions||[]).map(question=>[question.id,question])),[bank]);
  const profile=state?.profile,session=state?.activeSession,current=session?questionsById.get(session.questionIds[session.current]):null;
  const goalTests=useMemo(()=>profile?routeTests(profile) as TestKey[]:[],[profile]);
  const dueIds=useMemo(()=>state?dueReviewIds(state.reviewSchedule,questionsById,undefined,Date.now()) as string[]:[],[state,questionsById]);
  const readiness=useMemo(()=>bank&&state?Object.fromEntries(TEST_ORDER.map(test=>[test,readinessForTest({attempts:state.attempts,questionsById,test})]))as Record<TestKey,Ready>:null,[bank,state,questionsById]);
  const recommendation=useMemo(()=>bank&&state&&profile?nextRecommendation({profile,attempts:state.attempts,activeSession:state.activeSession,reviewSchedule:state.reviewSchedule,questionsById,definitions:bank.tests}):null,[bank,state,profile,questionsById]);
  const average=state?.attempts.length?Math.round(state.attempts.reduce((sum,item)=>sum+percent(item),0)/state.attempts.length):null;
  const weekDays=new Set((state?.activity||[]).filter(day=>new Date(`${day}T12:00:00`).getTime()>=Date.now()-6*86_400_000)).size;
  const updateState=(recipe:(value:RoadwiseState)=>RoadwiseState)=>setState(value=>value?recipe(value):value);
  const navigate=(next:View)=>{setResult(null);setShowSession(false);setView(next);location.hash=next;scrollTo(0,0)};

  const startStudy=(test:TestKey,kind:StudyKind)=>{
    if(!bank||!state)return;const count=kind==="exam"?bank.tests[test].questionCount:kind==="quick"?5:10;let selected:Question[];
    if(kind==="exam")selected=selectQuestions({questions:bank.questions,test,count,history:state.attempts,blueprint:bank.tests[test].blueprint} as any)as Question[];
    else if(kind==="review"){const due=dueReviewIds(state.reviewSchedule,questionsById,test,Date.now()).map((id:string)=>questionsById.get(id)).filter(Boolean)as Question[];const extra=(selectAdaptiveQuestions({questions:bank.questions,test,count,attempts:state.attempts,reviewSchedule:state.reviewSchedule} as any) as Question[]).filter(question=>!due.some(item=>item.id===question.id));selected=[...due,...extra].slice(0,count)}
    else selected=selectAdaptiveQuestions({questions:bank.questions,test,count,attempts:state.attempts,reviewSchedule:state.reviewSchedule} as any)as Question[];
    const activeSession:Session={test,kind,questionIds:selected.map(question=>question.id),orders:Object.fromEntries(selected.map(question=>[question.id,shuffle([0,1,2,3])])),answers:{},flagged:[],current:0,startedAt:Date.now()};
    updateState(value=>({...value,activeSession}));setResult(null);setShowSession(true);setReviewFilter("missed");location.hash="quiz";scrollTo(0,0);
  };
  const runRecommendation=()=>{if(!recommendation)return;if(recommendation.kind==="resume"){setShowSession(true);location.hash="quiz";return}startStudy(recommendation.test as TestKey,recommendation.kind==="maintain"?"quick":recommendation.kind as StudyKind)};
  const answer=(answerIndex:number)=>{if(!session||!current||session.kind!=="exam"&&session.answers[current.id]!==undefined)return;updateState(value=>{if(!value.activeSession)return value;return{...value,reviewSchedule:session.kind==="exam"?value.reviewSchedule:reviewQuestion(value.reviewSchedule,current.id,answerIndex===current.correctIndex),activeSession:{...value.activeSession,answers:{...value.activeSession.answers,[current.id]:answerIndex}}}})};
  const move=(index:number)=>updateState(value=>value.activeSession?({...value,activeSession:{...value.activeSession,current:Math.max(0,Math.min(value.activeSession.questionIds.length-1,index))}}):value);
  const toggleFlag=()=>{if(!session||!current)return;updateState(value=>value.activeSession?({...value,activeSession:{...value.activeSession,flagged:value.activeSession.flagged.includes(current.id)?value.activeSession.flagged.filter(id=>id!==current.id):[...value.activeSession.flagged,current.id]}}):value)};
  const submit=()=>{
    if(!session||!bank||!state)return;const unanswered=session.questionIds.length-Object.keys(session.answers).length;if(unanswered&&!confirm(`${unanswered} question${unanswered===1?" is":"s are"} unanswered. Submit anyway?`))return;
    const score=session.questionIds.filter(id=>session.answers[id]===questionsById.get(id)?.correctIndex).length,attempt:Attempt={id:String(Date.now()),test:session.test,mode:session.kind==="exam"?"exam":"learn",kind:session.kind,score,total:session.questionIds.length,passed:score>=Math.ceil(session.questionIds.length*.8),elapsed:Math.floor((Date.now()-session.startedAt)/1000),completedAt:Date.now(),answers:session.answers,questionIds:session.questionIds};
    let reviewSchedule=state.reviewSchedule;if(session.kind==="exam")for(const id of session.questionIds){const question=questionsById.get(id);reviewSchedule=reviewQuestion(reviewSchedule,id,session.answers[id]===question?.correctIndex)}const today=dayKey();
    updateState(value=>({...value,attempts:[attempt,...value.attempts].slice(0,100),reviewSchedule,activity:value.activity.includes(today)?value.activity:[...value.activity,today],activeSession:null}));setShowSession(false);setReviewFilter(score===session.questionIds.length?"all":"missed");setResult(attempt);location.hash="results";scrollTo(0,0);
  };
  const saveProfile=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget),name=String(form.get("name")||"").trim().replace(/\s+/g," ").slice(0,30);if(!name)return;const next:Profile={name,route:String(form.get("route")||"school")as RouteKey,airBrakes:form.get("airBrakes")==="on",weeklyTarget:Number(form.get("weeklyTarget")||4)};updateState(value=>({...value,profile:next}));setEditingProfile(false);navigate("home")};
  const exportBackup=()=>{if(!state)return;const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`roadwise-backup-${dayKey()}.json`;link.click();URL.revokeObjectURL(url)};
  const applyUpdate=()=>{if(!swRef.current?.waiting)return;navigator.serviceWorker.addEventListener("controllerchange",()=>location.reload(),{once:true});swRef.current.waiting.postMessage("SKIP_WAITING")};
  const importBackup=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());if(data.schemaVersion!==3||!data.profile||!Array.isArray(data.attempts)||!data.reviewSchedule)throw new Error();setState({...EMPTY_STATE,...data,activeSession:data.activeSession||null,settings:{...EMPTY_STATE.settings,...data.settings}});setImportMessage("Backup restored successfully.")}catch{setImportMessage("That file is not a valid Roadwise backup. Nothing was changed.")}finally{event.target.value=""}};

  if(!state||!bank)return <main className="loadingScreen"><Brand/><p>Preparing your Roadwise study plan...</p></main>;
  if(!profile||editingProfile)return <Onboarding state={state} onSubmit={saveProfile} onCancel={profile?()=>setEditingProfile(false):undefined}/>;
  if(showSession&&session&&current)return <Quiz bank={bank} session={session} current={current} elapsed={elapsed} onAnswer={answer} onMove={move} onFlag={toggleFlag} onSubmit={submit} onExit={()=>navigate("home")} onSource={setSourceQuestion} dialog={<SourceDialog question={sourceQuestion} bank={bank} online={online} dialogRef={dialogRef} onClose={()=>setSourceQuestion(null)}/>}/>;
  if(result)return <Results result={result} bank={bank} questionsById={questionsById} filter={reviewFilter} setFilter={setReviewFilter} onRetry={()=>startStudy(result.test,result.kind||result.mode)} onDone={()=>navigate("progress")} onSource={setSourceQuestion} dialog={<SourceDialog question={sourceQuestion} bank={bank} online={online} dialogRef={dialogRef} onClose={()=>setSourceQuestion(null)}/>}/>;

  const shared={bank,state,profile,goalTests,dueIds,readiness,questionsById,startStudy,navigate};
  const reset=()=>{if(confirm("Reset all Roadwise data on this device? This cannot be undone unless you have a backup.")){for(const key of[STATE_KEY,OLD_HISTORY_KEY,OLD_SESSION_KEY,"roadwise-progress","roadwise-user-name"])localStorage.removeItem(key);setState(EMPTY_STATE)}};
  const screen=view==="home"?<HomeScreen {...shared} recommendation={recommendation} runRecommendation={runRecommendation} average={average} weekDays={weekDays} updateReady={updateReady} applyUpdate={applyUpdate}/>:view==="study"?<StudyScreen {...shared}/>:view==="tests"?<TestsScreen {...shared}/>:view==="progress"?<ProgressScreen {...shared} average={average}/>:<SettingsScreen state={state} profile={profile} updateState={updateState} editProfile={()=>setEditingProfile(true)} exportBackup={exportBackup} importBackup={importBackup} importRef={importRef} importMessage={importMessage} reset={reset}/>;
  const completed=goalTests.filter(test=>readiness?.[test].ready).length;
  return <main className="appShell"><aside className="appSidebar"><Brand/><nav>{NAV.map(item=><button className={view===item.id?"active":""} key={item.id} onClick={()=>navigate(item.id)}><i>{item.icon}</i><span>{item.label}</span></button>)}</nav><div className="sidebarRoute"><small>YOUR ROUTE</small><b>{STUDY_ROUTES[profile.route].title}</b><span>{completed} of {goalTests.length} tests ready</span><i><b style={{width:`${goalTests.length?completed/goalTests.length*100:0}%`}}/></i></div><div className="offlineStatus"><i className={online?"online":""}/>{online?"Online":"Offline ready"}</div></aside><section className="appMain"><header className="topBar"><Brand/><div><small>ROADWISE CDL</small><b>{NAV.find(item=>item.id===view)?.label}</b></div><button onClick={()=>setEditingProfile(true)} aria-label="Edit profile">{profile.name.split(/\s+/).slice(0,2).map(part=>part[0]).join("").toUpperCase()}</button></header>{screen}</section><nav className="bottomNav">{NAV.map(item=><button className={view===item.id?"active":""} key={item.id} onClick={()=>navigate(item.id)} aria-current={view===item.id?"page":undefined}><i>{item.icon}</i><span>{item.label}</span>{item.id==="study"&&dueIds.length>0&&<b>{Math.min(dueIds.length,99)}</b>}</button>)}</nav><SourceDialog question={sourceQuestion} bank={bank} online={online} dialogRef={dialogRef} onClose={()=>setSourceQuestion(null)}/></main>;
}

function SettingsScreen({state,profile,updateState,editProfile,exportBackup,importBackup,importRef,importMessage,reset}:{state:RoadwiseState;profile:Profile;updateState:(recipe:(value:RoadwiseState)=>RoadwiseState)=>void;editProfile:()=>void;exportBackup:()=>void;importBackup:(event:ChangeEvent<HTMLInputElement>)=>void;importRef:React.RefObject<HTMLInputElement|null>;importMessage:string;reset:()=>void}){
  return <div className="screen settingsScreen"><ScreenHeader eyebrow="SETTINGS" title="Make Roadwise yours." description="Your information stays in this browser unless you export a backup."/><section><h2>Profile and study route</h2><div className="settingRow"><span><b>{profile.name}</b><small>{STUDY_ROUTES[profile.route].title} · {profile.airBrakes?"Air Brakes included":"Air Brakes not selected"}</small></span><button onClick={editProfile}>EDIT</button></div></section><section><h2>Study preferences</h2><label className="toggleRow"><span><b>Reduce motion</b><small>Limit interface animation and movement.</small></span><input type="checkbox" checked={state.settings.reducedMotion} onChange={event=>updateState(value=>({...value,settings:{...value.settings,reducedMotion:event.target.checked}}))}/></label></section><section><h2>Backup and restore</h2><p>Because Roadwise is device-only, save a backup before replacing or resetting this device.</p><div className="settingsActions"><button onClick={exportBackup}>DOWNLOAD BACKUP</button><button className="secondary" onClick={()=>importRef.current?.click()}>RESTORE BACKUP</button><input ref={importRef} type="file" accept="application/json" onChange={importBackup} hidden/></div>{importMessage&&<p className="importMessage" role="status">{importMessage}</p>}</section><section><h2>Install on iPad or iPhone</h2><p>Open Roadwise in Safari, tap Share, then choose Add to Home Screen. The installed app opens without normal browser controls and keeps the question bank available offline.</p></section><section className="dangerZone"><h2>Reset Roadwise</h2><p>This removes the profile, scores, review schedule, roadmap, and saved exam from this device.</p><button onClick={reset}>RESET ALL DATA</button></section></div>;
}

function Onboarding({state,onSubmit,onCancel}:{state:RoadwiseState;onSubmit:(event:FormEvent<HTMLFormElement>)=>void;onCancel?:()=>void}){
  const profile=state.profile;
  return <main className="onboardingShell"><section className="onboardingBrand"><Brand/><p>NEBRASKA CDL STUDY, BUILT AROUND YOU</p><h1>Pick your route.<br/><em>Build your score.</em></h1><span>Roadwise organizes the right tests, adaptive drills, and readiness milestones around your goal. Every test remains available.</span><div><b>540</b><span>original practice questions</span></div><div><b>5</b><span>full test subjects</span></div><div><b>100%</b><span>private on this device</span></div></section><form className="onboardingForm" onSubmit={onSubmit}><p>{profile?"EDIT YOUR PROFILE":"WELCOME TO ROADWISE"}</p><h2>{profile?"Update your study route":"Let’s set up your study plan."}</h2><label>Your name<input name="name" defaultValue={profile?.name||""} maxLength={30} autoComplete="name" autoFocus placeholder="Enter your name" required/></label><fieldset><legend>What are you working toward?</legend><div className="routeOptions">{Object.entries(STUDY_ROUTES).map(([key,route]:any)=><label key={key}><input type="radio" name="route" value={key} defaultChecked={(profile?.route||"school")===key}/><span><b>{route.title}</b><small>{route.description}</small></span></label>)}</div></fieldset><label className="checkOption"><input type="checkbox" name="airBrakes" defaultChecked={profile?.airBrakes!==false}/><span><b>Include Air Brakes</b><small>Select this when an air-brake vehicle applies to your goal.</small></span></label><label>Weekly study goal<select name="weeklyTarget" defaultValue={profile?.weeklyTarget||4}><option value="3">3 days per week</option><option value="4">4 days per week</option><option value="5">5 days per week</option><option value="7">Every day</option></select></label><button type="submit">{profile?"SAVE CHANGES":"BUILD MY STUDY PLAN"}</button>{onCancel&&<button type="button" className="cancelButton" onClick={onCancel}>Cancel</button>}<small>Your profile, scores, and study history stay in this browser.</small></form></main>;
}

function Quiz({bank,session,current,elapsed,onAnswer,onMove,onFlag,onSubmit,onExit,onSource,dialog}:{bank:Bank;session:Session;current:Question;elapsed:number;onAnswer:(answer:number)=>void;onMove:(index:number)=>void;onFlag:()=>void;onSubmit:()=>void;onExit:()=>void;onSource:(question:Question)=>void;dialog:React.ReactNode}){
  const revealed=session.kind!=="exam"&&session.answers[current.id]!==undefined;
  return <main className="quizShell"><header><button onClick={onExit}>EXIT</button><div><b>{bank.tests[session.test].title}</b><span>{session.kind==="exam"?"FULL EXAM":session.kind==="quick"?"QUICK 5":"LEARN MODE"} · {formatTime(elapsed)}</span></div><button className={session.flagged.includes(current.id)?"flagged":""} onClick={onFlag}>{session.flagged.includes(current.id)?"FLAGGED":"FLAG"}</button></header><div className="quizProgress"><i><b style={{width:`${Object.keys(session.answers).length/session.questionIds.length*100}%`}}/></i><span>{Object.keys(session.answers).length} of {session.questionIds.length} answered</span></div><div className="quizLayout"><aside>{session.questionIds.map((id,index)=><button key={id} onClick={()=>onMove(index)} className={`${index===session.current?"current ":""}${session.answers[id]!==undefined?"answered ":""}${session.flagged.includes(id)?"flagged":""}`} aria-label={`Question ${index+1}${session.answers[id]!==undefined?", answered":""}`}>{index+1}</button>)}</aside><article><p>QUESTION {session.current+1} OF {session.questionIds.length} · {current.topic} {current.difficulty==="technical"&&<b>TECHNICAL</b>}</p><h1>{current.prompt}</h1><div className="answers">{session.orders[current.id].map((answer,index)=>{const selected=session.answers[current.id]===answer,correct=revealed&&answer===current.correctIndex,wrong=revealed&&selected&&!correct;return <button key={answer} className={`${selected?"selected ":""}${correct?"correct ":""}${wrong?"wrong":""}`} onClick={()=>onAnswer(answer)}><i>{String.fromCharCode(65+index)}</i><span>{current.choices[answer]}</span></button>})}</div>{revealed&&<section className="explanation"><strong>{session.answers[current.id]===current.correctIndex?"Correct":"Review this one"}</strong><p>{current.explanation}</p><button onClick={()=>onSource(current)}>READ THE MANUAL REFERENCE</button></section>}<footer><button disabled={session.current===0} onClick={()=>onMove(session.current-1)}>PREVIOUS</button>{session.current===session.questionIds.length-1?<button className="primary" onClick={onSubmit}>SUBMIT</button>:<button className="primary" onClick={()=>onMove(session.current+1)}>NEXT</button>}</footer></article></div>{dialog}</main>;
}

function Results({result,bank,questionsById,filter,setFilter,onRetry,onDone,onSource,dialog}:{result:Attempt;bank:Bank;questionsById:Map<string,Question>;filter:"all"|"missed";setFilter:(value:"all"|"missed")=>void;onRetry:()=>void;onDone:()=>void;onSource:(question:Question)=>void;dialog:React.ReactNode}){
  const all=result.questionIds.map(id=>questionsById.get(id)).filter(Boolean)as Question[],missed=all.filter(question=>result.answers[question.id]!==question.correctIndex),visible=filter==="missed"?missed:all;
  return <main className="resultShell"><section className="resultPanel"><p>{result.mode==="exam"?"EXAM RESULTS":"STUDY RESULTS"}</p><div className={result.passed?"scoreSeal pass":"scoreSeal"}><strong>{percent(result)}%</strong><span>{result.passed?"PASS":"KEEP STUDYING"}</span></div><h1>{bank.tests[result.test].title}</h1><p>{result.score} of {result.total} correct · {formatTime(result.elapsed)}</p><div className="resultActions"><button onClick={onRetry}>TRY AGAIN</button><button className="secondary" onClick={onDone}>VIEW PROGRESS</button></div><section className="answerReview"><header><div><p>ANSWER REVIEW</p><h2>{filter==="missed"?"Missed answers":"All answers"}</h2></div><div><button className={filter==="missed"?"active":""} disabled={!missed.length} onClick={()=>setFilter("missed")}>MISSED ({missed.length})</button><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>ALL ({all.length})</button></div></header>{visible.length?visible.map(question=>{const selected=result.answers[question.id],correct=selected===question.correctIndex;return <article className={correct?"correct":"missed"} key={question.id}><small>{question.topic}</small><h3>{question.prompt}</h3><p><b>Your answer:</b> {selected===undefined?"Unanswered":question.choices[selected]}</p><p><b>Correct answer:</b> {question.choices[question.correctIndex]}</p><p>{question.explanation}</p><button className="sourceButton" onClick={()=>onSource(question)}>READ THE MANUAL REFERENCE</button></article>}):<p className="emptyState">No missed answers. Excellent work.</p>}</section></section>{dialog}</main>;
}

function SourceDialog({question,bank,online,dialogRef,onClose}:{question:Question|null;bank:Bank;online:boolean;dialogRef:React.RefObject<HTMLDialogElement|null>;onClose:()=>void}){
  if(!question)return null;
  return <dialog className="sourceDialog" ref={dialogRef} onClose={onClose} aria-labelledby="sourceTitle" onKeyDown={event=>{if(event.key==="Escape"){event.preventDefault();dialogRef.current?.close()}}}><div className="dialogHandle"/><header><div><p>MANUAL REFERENCE</p><h2 id="sourceTitle">Read deeper</h2></div><button onClick={()=>dialogRef.current?.close()} aria-label="Close manual reference">CLOSE</button></header><p className="sourcePrompt">{question.prompt}</p><div>{question.sourceIds.map(sourceId=>{const source=bank.sources[sourceId],manual=source&&bank.manuals[source.manualId];if(!source||!manual)return null;return <article key={sourceId}><small>{manual.title}</small><h3>{source.section}</h3><div className="pageBadge"><b>{source.printedPage}</b><span>PDF page {source.pdfPage} of {manual.totalPages}</span></div><p>{source.studySummary}</p>{online?<a href={`${manual.officialUrl}#page=${source.pdfPage}`} target="_blank" rel="noreferrer">OPEN OFFICIAL MANUAL AT THIS PAGE</a>:<button disabled>INTERNET REQUIRED FOR THE OFFICIAL PDF</button>}</article>})}</div><footer>Roadwise summaries are original study guidance. Official manuals open separately and are not stored in this app.</footer></dialog>;
}
